<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s and you';
$Definition['%s comment'] = '%s comment';
$Definition['%s comments'] = '%s comments';
$Definition['%s Connect'] = '%s Connect';
$Definition['%s message'] = '%s message';
$Definition['%s New'] = '%s New';
$Definition['%s new'] = '%s new';
$Definition['%s New Plural'] = '%s New';

$Definition['1 message'] = '1 message';

$Definition['About'] = 'About';
$Definition['Accepted'] = 'Accepted';
$Definition['Activity'] = 'Activity';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s updated %6$s profile.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s added you to a %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s added  you to a %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s commented on your %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s commented on your %8$s.';
$Definition['Activity.Comment'] = 'Comment';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s sent you a %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s sent you a %8$s.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s commented on %4$s %8$s.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s imported data.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s imported data.';
$Definition['Activity.Join.FullHeadline'] = '%1$s joined.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s joined.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s approved %4$s membership application.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s created an account for %1$s.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s accepted %4$s invitation for membership.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s started a %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s started a %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s changed %6$s profile picture.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s changed %6$s profile picture.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s changed %4$s permissions.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s signed in.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s signed in.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s wrote on %4$s %5$s.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s wrote:';
$Definition['Add'] = 'Add';
$Definition['Add Comment'] = 'Add Comment';
$Definition['Add Info &amp; Create Account'] = 'Add Info &amp; Create Account';
$Definition['Add Message'] = 'Add Message';
$Definition['Add People to this Conversation'] = 'Add People to this Conversation';
$Definition['All Conversations'] = 'All Conversations';
$Definition['All Discussions'] = 'All Discussions';
$Definition['Allow other members to see your email?'] = 'Allow other members to see your email?';
$Definition['Announce'] = 'Announce';
$Definition['Applicants'] = 'Applicants';
$Definition['Apply'] = 'Apply';
$Definition['Apply for Membership'] = 'Apply for Membership';
$Definition['Are you sure you want to do that?'] = 'Are you sure you want to do that?';
$Definition['at'] = 'at';

$Definition['Back to Discussions'] = 'Back to Discussions';
$Definition['Bookmark'] = 'Bookmark';
$Definition['bookmarked discussion'] = 'bookmarked discussion';
$Definition['Bookmarked Discussions'] = 'Bookmarked Discussions';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.';

$Definition['Cancel'] = 'Cancel';
$Definition['Categories'] = 'Categories';
$Definition['Category'] = 'Category';
$Definition['Change My Password'] = 'Change My Password';
$Definition['Change My Picture'] = 'Change My Picture';
$Definition['Close'] = 'Close';
$Definition['comment'] = 'comment';
$Definition['Comment'] = 'Comment';
$Definition['Confirm'] = 'Confirm';
$Definition['Confirm Password'] = 'Confirm Password';
$Definition['Connect'] = 'Connect';
$Definition['conversation'] = 'conversation';
$Definition['Conversations'] = 'Conversations';
$Definition['Create One.'] = 'Create One.';

$Definition['Dashboard'] = 'Dashboard';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'Delete';
$Definition['Delete Account'] = 'Delete Account';
$Definition['Delete Conversation'] = 'Delete Conversation';
$Definition['Delete Discussion'] = 'Delete Discussion';
$Definition['discussion'] = 'discussion';
$Definition['Discussion Title'] = 'Discussion Title';
$Definition['Discussions'] = 'Discussions';
$Definition['Don\'t have an account? %s'] = 'Don\'t have an account? %s';
$Definition['dot'] = 'dot';
$Definition['Draft saved at %s'] = 'Draft saved at %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Drag around and resize the square below to define your thumbnail icon.';

$Definition['Edit'] = 'Edit';
$Definition['Edit Account'] = 'Edit Account';
$Definition['Edit My Account'] = 'Edit My Account';
$Definition['Edit My Thumbnail'] = 'Edit My Thumbnail';
$Definition['Edit Preferences'] = 'Edit Preferences';
$Definition['Email'] = 'Email';
$Definition['Email Notifications'] = 'Email Notifications';
$Definition['Email Unavailable'] = 'Email Unavailable';
$Definition['EmailHeader'] = 'Hello {User.Name}!
';
$Definition['EmailFooter'] = '
Have a great day!';

$Definition['EmailInvitation'] = 'Hello!

%1$s has invited you to join %2$s. If you want to join, you can do so by clicking this link:

  %3$s';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

  %2$s';
$Definition['EmailWelcome'] = '%2$s has created an account for you at %3$s. Your login credentials are:

  Email: %6$s
  Password: %5$s
  Url: %4$s';
$Definition['EmailPassword'] = '%2$s has reset your password at %3$s. Your login credentials are now:

  Email: %6$s
  Password: %5$s
  Url: %4$s';
$Definition['EmailConfirmEmail'] = 'You need to confirm your email address before you can continue. Please confirm your email address by clicking on the following link: {/entry/emailconfirm,url,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailWelcomeRegister'] = 'You have successfully registered for an account at {Title}. Here is your information:

  Username: {User.Name}
  Email: {User.Email}

You can access the site at {/,url,domain}.';
$Definition['EmailWelcomeConnect'] = 'You have successfully connected to {Title}. Here is your information:

  Username: {User.Name}
  Connected With: {ProviderName}

You can access the site at {/,url,domain}.';
$Definition['PasswordRequest'] = 'Someone has requested to reset your password at %2$s. To reset your password, follow this link:

  %3$s

If you did not make this request, disregard this email.';
$Definition['EmailNotification'] = '%1$s

Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['Enter the email address of the person you would like to invite:'] = 'Enter the email address of the person you would like to invite:';
$Definition['Enter your Email address'] = 'Enter your Email address';
$Definition['Enter your existing account password.'] = 'Enter your existing account password.';
$Definition['ErrorCredentials'] = 'Sorry, no account could be found related to the email and password you entered.';
$Definition['ErrorPermission'] = 'Sorry, permission denied.';
$Definition['ErrorRecordNotFound'] = 'The requested record could not be found.';
$Definition['ErrorTermsOfService'] = 'You must agree to the terms of service.';

$Definition['Female'] = 'Female';
$Definition['Forgot?'] = 'Forgot?';

$Definition['Gender'] = 'Gender';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Go';
$Definition['GuestModule.Message'] = 'It looks like you\'re new here. If you want to get involved, click one of these buttons!';

$Definition['he'] = 'he';
$Definition['her'] = 'her';
$Definition['his'] = 'his';
$Definition['Howdy, Stranger!'] = 'Howdy, Stranger!';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>';
$Definition['I remember now!'] = 'I remember now!';
$Definition['In this Conversation'] = 'In this Conversation';
$Definition['Inbox'] = 'Inbox';
$Definition['Internal'] = 'Internal';
$Definition['Invitation Code'] = 'Invitation Code';
$Definition['Invite'] = 'Invite';
$Definition['Invited by'] = 'Invited by';

$Definition['Joined'] = 'Joined';

$Definition['Keep me signed in'] = 'Keep me signed in';

$Definition['Last Active'] = 'Last Active';
$Definition['Login with Facebook'] = 'Login with Facebook';

$Definition['Male'] = 'Male';
$Definition['Most recent by %1$s'] = 'Most recent by %1$s';
$Definition['My Bookmarks'] = 'My Bookmarks';
$Definition['My Discussions'] = 'My Discussions';
$Definition['My Drafts'] = 'My Drafts';
$Definition['My Invitations'] = 'My Invitations';
$Definition['My Preferences'] = 'My Preferences';

$Definition['Name Unavailable'] = 'Name Unavailable';
$Definition['No discussions were found.'] = 'No discussions were found.';
$Definition['Notifications'] = 'Notifications';
$Definition['Notify me of private messages.'] = 'Notify me of private messages.';
$Definition['Notify me when I am added to private conversations.'] = 'Notify me when I am added to private conversations.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Notify me when people comment on my bookmarked discussions.';
$Definition['Notify me when people comment on my discussions.'] = 'Notify me when people comment on my discussions.';
$Definition['Notify me when people mention me in comments.'] = 'Notify me when people mention me in comments.';
$Definition['Notify me when people mention me in discussion titles.'] = 'Notify me when people mention me in discussion titles.';
$Definition['Notify me when people reply to my wall comments.'] = 'Notify me when people reply to my wall comments.';
$Definition['Notify me when people write on my wall.'] = 'Notify me when people write on my wall.';

$Definition['Okay'] = 'Okay';
$Definition['On'] = 'On';
$Definition['Options'] = 'Options';
$Definition['Or you can...'] = 'Or you can...';
$Definition['Original'] = 'Original';

$Definition['PageDetailsMessage'] = '%1$s to %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s to %2$s of %3$s';
$Definition['Password'] = 'Password';
$Definition['PasswordRequest'] = 'Hello %1$s,

Someone has requested to reset your password at %2$s. To reset your password, follow this link:

  %3$s

If you did not make this request, disregard this email.';
$Definition['Passwords don\'t match'] = 'Passwords don\'t match';
$Definition['Permalink'] = 'Permalink';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.';
$Definition['Post Comment'] = 'Post Comment';
$Definition['Post Discussion'] = 'Post Discussion';
$Definition['Powered by Vanilla'] = 'Powered by Vanilla';
$Definition['Preview'] = 'Preview';
$Definition['Profile Picture'] = 'Profile Picture';

$Definition['Recent Activity'] = 'Recent Activity';
$Definition['Recipients'] = 'Recipients';
$Definition['Redirecting...'] = 'Redirecting...';
$Definition['Remember me on this computer'] = 'Remember me on this computer';
$Definition['Remove My Picture'] = 'Remove My Picture';
$Definition['Request a new password'] = 'Request a new password';
$Definition['Roles'] = 'Roles';

$Definition['Save'] = 'Save';
$Definition['Save Draft'] = 'Save Draft';
$Definition['Save Preferences'] = 'Save Preferences';
$Definition['Search'] = 'Search';
$Definition['Select an image on your computer (2mb max)'] = 'Select an image on your computer (2mb max)';
$Definition['Send %s a Message'] = 'Send %s a Message';
$Definition['Send Message'] = 'Send Message';
$Definition['Sent To'] = 'Sent To';
$Definition['Share'] = 'Share';
$Definition['she'] = 'she';
$Definition['Sign In'] = 'Sign In';
$Definition['Sign In with Google'] = 'Sign In with Google';
$Definition['Sign In with OpenID'] = 'Sign In with OpenID';
$Definition['Sign In with Twitter'] = 'Sign In with Twitter';
$Definition['Sign Out'] = 'Sign Out';
$Definition['Sign Up'] = 'Sign Up';
$Definition['Sink'] = 'Sink';
$Definition['somebody'] = 'somebody';
$Definition['Start a New Conversation'] = 'Start a New Conversation';
$Definition['Start a New Discussion'] = 'Start a New Discussion';
$Definition['Start Conversation'] = 'Start Conversation';
$Definition['Started by %1$s'] = 'Started by %1$s';
$Definition['Status'] = 'Status';

$Definition['Thank You!'] = 'Thank You!';
$Definition['Thumbnail'] = 'Thumbnail';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';

$Definition['Unbookmark'] = 'Unbookmark';
$Definition['Upload'] = 'Upload';
$Definition['Username'] = 'Username';

$Definition['ValidateBoolean'] = '%s is not a valid boolean.';
$Definition['ValidateConnection'] = 'The connection parameters you specified failed to open a connection to the database. The database reported the following error: <code>%s</code>';
$Definition['ValidateDate'] = '%s is not a valid date.';
$Definition['ValidateDecimal'] = '%s is not a valid decimal.';
$Definition['ValidateEmail'] = '%s does not appear to be valid.';
$Definition['ValidateEnum'] = '%s is not valid.';
$Definition['ValidateInteger'] = '%s is not a valid integer.';
$Definition['ValidateLength'] = '%1$s is %2$s characters too long.';
$Definition['ValidateMatch'] = 'The %s fields do not match.';
$Definition['ValidateMinimumAge'] = 'You must be at least 16 years old to proceed.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'You must select at least one %s.';
$Definition['ValidateRegex'] = '%s does not appear to be in the correct format.';
$Definition['ValidateRequired'] = '%s is required.';
$Definition['ValidateRequiredArray'] = 'You must select at least one %s.';
$Definition['ValidateTime'] = '%s is not a valid time.';
$Definition['ValidateTimestamp'] = '%s is not a valid timestamp.';
$Definition['ValidateUsername'] = 'Usernames must be 3-20 characters and consist of letters, numbers, and underscores.';
$Definition['ValidateVersion'] = 'The %s field is not a valid version number. See the php version_compare() function for examples of valid version numbers.';
$Definition['Visits'] = 'Visits';

$Definition['wall'] = 'wall';
$Definition['Why do you want to join?'] = 'Why do you want to join?';
$Definition['Write a comment'] = 'Write a comment';
$Definition['Write Comment'] = 'Write Comment';
$Definition['Write something about yourself...'] = 'Write something about yourself...';

$Definition['you'] = 'you';
$Definition['You'] = 'You';
$Definition['You already have an account here.'] = 'You already have an account here.';
$Definition['You are connected as %s through %s.'] = 'You are connected as %s through %s.';
$Definition['You do not have any conversations.'] = 'You do not have any conversations.';
$Definition['You do not have any notifications yet.'] = 'You do not have any notifications yet.';
$Definition['your'] = 'your';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'Your application will be reviewed by an administrator. You will be notified by email if your application is approved.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Your registered username: <strong>%s</strong>';

$Definition['Save Comment'] = 'Save Comment';
$Definition['Unannounce'] = 'Unannounce';
$Definition['Announcement'] = 'Announcement';
$Definition['Dismiss'] = 'Dismiss';
$Definition['Closed'] = 'Closed' ;
$Definition['Reopen'] = 'Reopen';
$Definition['Old Password'] = 'Old Password';
$Definition['New Password'] = 'New Password';
$Definition['Change Password'] = 'Change Password';
$Definition['Add a Comment'] = 'Add a Comment';
$Definition['Edit Discussion'] = 'Edit Discussion';
$Definition['Uninvite'] = 'Uninvite';
$Definition['Send Again'] = 'Send Again';
$Definition['Pending'] = 'Pending';