<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:58 **/


$Definition['%1$s on %2$s'] = '%1$s on %2$s';
$Definition['%1$s Version %2$s'] = '%1$s Version %2$s';
$Definition['%s user(s) found.'] = '%s user(s) found.';

$Definition['(YYYY-mm-dd)'] = '(YYYY-mm-dd)';

$Definition['1 month after being sent'] = '1 month after being sent';
$Definition['1 week after being sent'] = '1 week after being sent';

$Definition['2 weeks after being sent'] = '2 weeks after being sent';

$Definition['<General Error>'] = '<General Error>';
$Definition['<strong>%1$s</strong> (%2$s) %3$s'] = '<strong>%1$s</strong> (%2$s) %3$s';
$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:'] = '<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:';

$Definition['[%1$s] Membership Approved'] = '[%1$s] Membership Approved';

$Definition['_Locale'] = 'Locale';

$Definition['A url-friendly version of the category name for better SEO.'] = 'A url-friendly version of the category name for better SEO.';
$Definition['Action'] = 'Action';
$Definition['Activate'] = 'Activate';
$Definition['Add'] = 'Add';
$Definition['Add Message'] = 'Add Message';
$Definition['Add Route'] = 'Add Route';
$Definition['Add User'] = 'Add User';
$Definition['Addons'] = 'Addons';
$Definition['Administrator'] = 'Administrator';
$Definition['Advanced'] = 'Advanced';
$Definition['Advanced Forum Settings'] = 'Advanced Forum Settings';
$Definition['All <span>16</span>'] = 'All <span>16</span>';
$Definition['All <span>2</span>'] = 'All <span>2</span>';
$Definition['Announce'] = 'Announce';
$Definition['Appearance'] = 'Appearance';
$Definition['Applicant'] = 'Applicant';
$Definition['Applicants'] = 'Applicants';
$Definition['Application'] = 'Application';
$Definition['Application ID'] = 'Application ID';
$Definition['Application Secret'] = 'Application Secret';
$Definition['ApplicationHelp'] = 'Applications allow you to add large groups of functionality to your site.<br />Once an application has been added to your %s folder, you can enable or disable it here.';
$Definition['Applications'] = 'Applications';
$Definition['Approve'] = 'Approve';
$Definition['Archive Discussions'] = 'Archive Discussions';
$Definition['Are you sure you want to do that?'] = 'Are you sure you want to do that?';
$Definition['at'] = 'at';
$Definition['Authentication'] = 'Authentication';

$Definition['Banned'] = 'Banned';
$Definition['Banner'] = 'Banner';
$Definition['Banner Logo'] = 'Banner Logo';
$Definition['Banner Title'] = 'Banner Title';

$Definition['Cancel'] = 'Cancel';
$Definition['Capture locale pack changes.'] = 'Capture the changes between one of your locale packs and the Locale Developer. It will be put in the <code>changes.php</code> file.';
$Definition['Categories'] = 'Categories';
$Definition['Categories are used to help organize discussions. '] = 'Categories are used to help organize discussions. ';
$Definition['Category'] = 'Category';
$Definition['Category Url:'] = 'Category Url:';
$Definition['Change the way that new users register with the site.'] = 'Change the way that new users register with the site.';
$Definition['Check all permissions that apply for each role'] = 'Check all permissions that apply for each role';
$Definition['Check all roles that apply to this user:'] = 'Check all roles that apply to this user:';
$Definition['Choose a locale pack'] = 'Choose a locale pack';
$Definition['Choose and configure your forum\'s authentication scheme.'] = 'Choose and configure your forum\'s authentication scheme.';
$Definition['Choose who can send out invitations to new members:'] = 'Choose who can send out invitations to new members:';
$Definition['Close'] = 'Close';
$Definition['comment(s)'] = 'comment(s)';
$Definition['Comments'] = 'Comments';
$Definition['Comments per Page'] = 'Comments per Page';
$Definition['Configure an Authenticator'] = 'Configure an Authenticator';
$Definition['Confirm'] = 'Confirm';
$Definition['Confirm Email'] = 'Confirm Email';
$Definition['Consumer Key'] = 'Consumer Key';
$Definition['Consumer Secret'] = 'Consumer Secret';
$Definition['Conversation Messages'] = 'Conversation Messages';
$Definition['Conversations'] = 'Conversations';
$Definition['Copy'] = 'Copy';
$Definition['Copy locale pack.'] = 'Copy the definitions from a locale pack to the Locale Developer. The definitions will be put in the <code>copied.php</code> file.';
$Definition['Current Authenticator'] = 'Current Authenticator';
$Definition['Current Theme'] = 'Current Theme';
$Definition['Customize your Public Profile'] = 'Customize your Public Profile';

$Definition['Dashboard'] = 'Dashboard';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Decline'] = 'Decline';
$Definition['Delete'] = 'Delete';
$Definition['Description'] = 'Description';
$Definition['Disable'] = 'Disable';
$Definition['Disable Google Sign In'] = 'Disable Google Sign In';
$Definition['Disable OpenID'] = 'Disable OpenID';
$Definition['Disabled <span>0</span>'] = 'Disabled <span>0</span>';
$Definition['Disabled <span>10</span>'] = 'Disabled <span>10</span>';
$Definition['Disabled <span>11</span>'] = 'Disabled <span>11</span>';
$Definition['Disabled <span>12</span>'] = 'Disabled <span>12</span>';
$Definition['Disabled <span>9</span>'] = 'Disabled <span>9</span>';
$Definition['Discussion & Comment Editing'] = 'Discussion & Comment Editing';
$Definition['discussion(s)'] = 'discussion(s)';
$Definition['Discussions'] = 'Discussions';
$Definition['Discussions per Page'] = 'Discussions per Page';
$Definition['dot'] = 'dot';

$Definition['Edit'] = 'Edit';
$Definition['edit'] = 'edit';
$Definition['Edit Category'] = 'Edit Category';
$Definition['Edit User'] = 'Edit User';
$Definition['EditContentTimeout.Notes'] = 'Note: If a user is in a role that has permission to edit content, those permissions will override any value selected here.';
$Definition['Email'] = 'Email';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Email sent from the application will be addressed from the following name and address';
$Definition['Email visible to other users'] = 'Email visible to other users';
$Definition['EmailMembershipApproved'] = 'Hello %1$s,

You have been approved for membership. Sign in now at the following link:

  %2$s
  
Have a great day!';
$Definition['Enable'] = 'Enable';
$Definition['Enable Google Sign In'] = 'Enable Google Sign In';
$Definition['Enable OpenID'] = 'Enable OpenID';
$Definition['Enabled <span>2</span>'] = 'Enabled <span>2</span>';
$Definition['Enabled <span>4</span>'] = 'Enabled <span>4</span>';
$Definition['Enabled <span>5</span>'] = 'Enabled <span>5</span>';
$Definition['Enabled <span>6</span>'] = 'Enabled <span>6</span>';
$Definition['Enabled <span>7</span>'] = 'Enabled <span>7</span>';
$Definition['Existing members send invitations to new members.'] = 'Existing members send invitations to new members.';

$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = 'Facebook Connect allows users to sign in using their Facebook account. <b>You must register your application with Facebook for this plugin to work.</b>';
$Definition['Facebook Settings'] = 'Facebook Settings';
$Definition['First Visit'] = 'First Visit';
$Definition['For more help on localization check out the page <a href="%s">here</a>.'] = 'For more help on localization check out the page <a href="%s">here</a>.';
$Definition['Forum Settings'] = 'Forum Settings';

$Definition['Garden.Email.SupportAddress'] = 'Support email';
$Definition['Garden.Import.Description'] = 'Use this page to import data from another forum that was exported using Vanilla\'s exporter. For more information <a href="%s">see our importing documentation</a>.';
$Definition['Garden.Import.InputInstructions'] = 'Enter the email and password of the admin user from the data being imported.';
$Definition['Garden.Import.Overwrite.Description'] = 'Warning: All data in this forum will be overwritten.';
$Definition['Generate'] = 'Generate';
$Definition['Generate Password'] = 'Generate Password';
$Definition['Go'] = 'Go';
$Definition['Google Sign In Settings'] = 'Google Sign In Settings';
$Definition['Guest'] = 'Guest';

$Definition['here'] = 'here';

$Definition['Import'] = 'Import';
$Definition['Inbox'] = 'Inbox';
$Definition['Information'] = 'Information';
$Definition['Internal'] = 'Internal';
$Definition['Invitations can be sent from users\' profile pages.'] = 'When you use registration by invitation users will have a link called <a href="%s" class="Popup">My Invitations</a> on their profile pages.';
$Definition['Invitations per month'] = 'Invitations per month';
$Definition['Invitations will expire'] = 'Invitations will expire';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.';

$Definition['Key Type'] = 'Key Type';
$Definition['Key Value'] = 'Key Value';

$Definition['Last Active'] = 'Last Active';
$Definition['Last Visit'] = 'Last Visit';
$Definition['Locale Developer'] = 'Locale Developer';
$Definition['Locale Developer Settings %s.'] = 'Locale Developer Settings %s.';
$Definition['Locale info file settings.'] = '<p>When you generate the zip file you can set the information for the locale below.</p> <p>You can download a zip of the locale pack by clicking <a href="%s">here</a>.</p>';
$Definition['Locale Key (Folder)'] = 'Locale Key (Folder)';
$Definition['Locale Name'] = 'Locale Name';
$Definition['Locales'] = 'Locales';
$Definition['Locales are in your %s folder.'] = 'Locales allow you to support other languages on your site. Once an locale has been added to your %s folder, you can enable or disable it here.';
$Definition['Location'] = 'Location';

$Definition['Manage Applicants'] = 'Manage Applicants';
$Definition['Manage Applications'] = 'Manage Applications';
$Definition['Manage Categories'] = 'Manage Categories';
$Definition['Manage Messages'] = 'Manage Messages';
$Definition['Manage Plugins'] = 'Manage Plugins';
$Definition['Manage Roles & Permissions'] = 'Manage Roles & Permissions';
$Definition['Manage Routes'] = 'Manage Routes';
$Definition['Manage Spam'] = 'Manage Spam';
$Definition['Manage Themes'] = 'Manage Themes';
$Definition['Manage Users'] = 'Manage Users';
$Definition['Manage your Plugins'] = 'Manage your Plugins';
$Definition['Max Comment Length'] = 'Max Comment Length';
$Definition['Member'] = 'Member';
$Definition['Message'] = 'Message';
$Definition['Messages'] = 'Messages';
$Definition['Messages can appear anywhere in your application.'] = 'Messages can appear anywhere in your application, and can be used to inform your users of news and events. Use this page to re-organize your messages by dragging them up or down.';
$Definition['Method'] = 'Method';
$Definition['minute(s)'] = 'minute(s)';
$Definition['Moderator'] = 'Moderator';

$Definition['Name'] = 'Name';
$Definition['never'] = 'never';
$Definition['New comments in the last day'] = 'New comments in the last day';
$Definition['New comments in the last week'] = 'New comments in the last week';
$Definition['New conversations in the last day'] = 'New conversations in the last day';
$Definition['New conversations in the last week'] = 'New conversations in the last week';
$Definition['New discussions in the last day'] = 'New discussions in the last day';
$Definition['New discussions in the last week'] = 'New discussions in the last week';
$Definition['New messages in the last day'] = 'New messages in the last day';
$Definition['New messages in the last week'] = 'New messages in the last week';
$Definition['New Password'] = 'New Password';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'New users are reviewed and approved by an administrator (that\'s you!).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'New users fill out a simple form and are granted access immediately.';
$Definition['New users in the last day'] = 'New users in the last day';
$Definition['New users in the last week'] = 'New users in the last week';
$Definition['None'] = 'None';
$Definition['Not Authorized (401)'] = 'Not Authorized (401)';
$Definition['Not Found (404)'] = 'Not Found (404)';

$Definition['OK'] = 'OK';
$Definition['Okay'] = 'Okay';
$Definition['Only Allow Each User To Post'] = 'Only Allow Each User To Post';
$Definition['OpenID Settings'] = 'OpenID Settings';
$Definition['Options'] = 'Options';
$Definition['Or Spamblock For'] = 'Or Spamblock For';
$Definition['Organize your Categories'] = 'Organize your Categories';
$Definition['Other Themes'] = 'Other Themes';
$Definition['Outgoing Email'] = 'Outgoing Email';

$Definition['Page'] = 'Page';
$Definition['Panel Box'] = 'Panel Box';
$Definition['Password'] = 'Password';
$Definition['Password Options'] = 'Password Options';
$Definition['Permanent (301)'] = 'Permanent (301)';
$Definition['Please choose an authenticator to configure.'] = 'Please choose an authenticator to configure.';
$Definition['Plugin'] = 'Plugin';
$Definition['PluginHelp'] = 'Plugins allow you to add functionality to your site.<br />Once a plugin has been added to your %s folder, you can enable or disable it here.';
$Definition['Plugins'] = 'Plugins';
$Definition['Position'] = 'Position';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.';
$Definition['Private Key'] = 'Private Key';
$Definition['Public Key'] = 'Public Key';

$Definition['Recently Active Users'] = 'Recently Active Users';
$Definition['Refresh Comments'] = 'Refresh Comments';
$Definition['Registration'] = 'Registration';
$Definition['Remove'] = 'Remove';
$Definition['Remove locale developer files.'] = 'Remove the locale deveoper files and reset your changes.';
$Definition['Requires: '] = 'Requires: ';
$Definition['Reset Password'] = 'Reset Password';
$Definition['Reset password and send email notification to user'] = 'Reset password and send email notification to user';
$Definition['Reveal Password'] = 'Reveal Password';
$Definition['Role'] = 'Role';
$Definition['Roles & Permissions'] = 'Roles & Permissions';
$Definition['Roles determine user\'s permissions.'] = 'Every user in your site is assigned to at least one role. Roles are used to determine what the users are allowed to do.';
$Definition['Route'] = 'Route';
$Definition['Route Expression'] = 'Route Expression';
$Definition['Routes'] = 'Routes';
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = 'Routes can be used to redirect users to various parts of your site depending on the url.';

$Definition['Save'] = 'Save';
$Definition['Search'] = 'Search';
$Definition['seconds'] = 'seconds';
$Definition['Select the file to import'] = 'Select the file to import';
$Definition['Settings'] = 'Settings';
$Definition['Sign Out'] = 'Sign Out';
$Definition['Sink'] = 'Sink';
$Definition['SMTP Host'] = 'SMTP Host';
$Definition['SMTP Password'] = 'SMTP Password';
$Definition['SMTP Port'] = 'SMTP Port';
$Definition['SMTP Security'] = 'SMTP Security';
$Definition['SMTP User'] = 'SMTP User';
$Definition['Spam'] = 'Spam';
$Definition['Start your First Discussion'] = 'Start your First Discussion';

$Definition['Target'] = 'Target';
$Definition['Temporary (302)'] = 'Temporary (302)';
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'The %s Authenticator does not have any custom configuration options.';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'The addon could not be enabled because it generated a fatal error: <pre>%s</pre>';
$Definition['The banner logo appears at the top of your forum.'] = 'The banner logo appears at the top of your forum.';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.';
$Definition['The file failed to upload.'] = 'The file failed to upload.';
$Definition['ThemeHelp'] = 'Themes allow you to change the look &amp; feel of your site.<br />Once a theme has been added to your %s folder, you can enable it here.';
$Definition['Themes'] = 'Themes';
$Definition['There are currently no applicants.'] = 'There are currently no applicants.';
$Definition['This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.'] = 'This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.';
$Definition['This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.'] = 'This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.';
$Definition['This plugin helps locale package development.'] = 'This plugin helps locale package development. The plugin keeps a working locale pack at <code>%s</code>.';
$Definition['Tools'] = 'Tools';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = 'Twitter Connect allows users to sign in using their Twitter account. <b>You must register your application with Twitter for this plugin to work.</b>';
$Definition['Twitter Settings'] = 'Twitter Settings';
$Definition['Type'] = 'Type';

$Definition['Unlimited'] = 'Unlimited';
$Definition['Upload'] = 'Upload';
$Definition['Url'] = 'Url';
$Definition['User'] = 'User';
$Definition['User Registration Settings'] = 'User Registration Settings';
$Definition['Username'] = 'Username';
$Definition['Users'] = 'Users';

$Definition['ValidateRequired'] = '%s is required.';
$Definition['Vanilla.Archive.Description'] = 'You can choose to archive forum discussions older than a certain date. Archived discussions are effectively closed, allowing no new posts.';
$Definition['Version'] = 'Version';
$Definition['Version %s'] = 'Version %s';
$Definition['version %s'] = 'version %s';
$Definition['View'] = 'View';
$Definition['Visit Site'] = 'Visit Site';

$Definition['Warning'] = 'Warning';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.';
$Definition['Welcome Aboard!'] = 'Welcome Aboard!';
$Definition['What\'s the Buzz?'] = 'What\'s the Buzz?';
$Definition['Within'] = 'Within';

$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'If you are ever locked out of your forum you can always log in using your original Vanilla email and password at <a href="%1$s">%1$s</a>';
$Definition['You can place files in your /uploads folder.'] = 'If your file is too
		large to upload directly to this page you can place it in your /uploads
		folder. Make sure the filename begins with the word <b>export</b> and ends
		with one of <b>.txt, .gz</b>.';
$Definition['You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.'] = 'You cannot disable the %1$s plugin because the %2$s plugin requires it in order to function.';
$Definition['You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.'] = 'You cannot disable the OpenID plugin because the GoogleSignIn plugin requires it in order to function.';
$Definition['Your changes have been saved.'] = 'Your changes have been saved.';
$Definition['Your settings have been saved.'] = 'Your settings have been saved.';
