<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:23:07 **/

$LocaleInfo['Greek'] = array (
  'Locale' => 'el-GR',
  'Name' => 'Greek',
  'Description' => 'ελληνικά',
  'Version' => '1.0.1b',
  'Author' => 'Argyris Argyrou',
  'AuthorEmail' => 'argyris@wadja.com',
  'AuthorUrl' => 'http://vanillaforums.org/profile/argyris',
  'License' => 'GPL2',
);

