<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2010-11-23 12:22:01 **/


$Definition['%s and you'] = '%s και εσύ';
$Definition['%s comment'] = '%s σχόλιο';
$Definition['%s comments'] = '%s σχόλια';
$Definition['%s Connect'] = '%s Συνδέσου';
$Definition['%s message'] = '%s μήνυμα';
$Definition['%s New'] = '%s New';
$Definition['%s new'] = '%s new';
$Definition['%s New Plural'] = '%s Πληθυντικός';

$Definition['1 message'] = '1 μήνυμα';

$Definition['About'] = 'About';
$Definition['Accepted'] = 'Δεκτόν';
$Definition['Activity'] = 'Δραστηριότητα';
$Definition['Activity.AboutUpdate.FullHeadline'] = '%1$s αναβάθμιση %6$s προφίλ.';
$Definition['Activity.AboutUpdate.ProfileHeadline'] = '%1$s αναβάθμιση %6$s προφίλ.';
$Definition['Activity.ActivityComment.FullHeadline'] = '%1$s σχολίασε για %4$s %8$s.';
$Definition['Activity.ActivityComment.ProfileHeadline'] = '%1$s';
$Definition['Activity.AddedToConversation.FullHeadline'] = '%1$s σε πρόσθεσε σε ένα %8$s.';
$Definition['Activity.AddedToConversation.ProfileHeadline'] = '%1$s σε πρόσθεσε σε ένα %8$s.';
$Definition['Activity.BookmarkComment.FullHeadline'] = '%1$s σχολίασε πάνω στο %8$s.';
$Definition['Activity.BookmarkComment.ProfileHeadline'] = '%1$s σχολίασε πάνω στο %8$s.';
$Definition['Activity.Comment'] = 'Comment';
$Definition['Activity.CommentMention.FullHeadline'] = '%1$s αναφέρθηκε %3$s μέσα σε ένα %8$s.';
$Definition['Activity.CommentMention.ProfileHeadline'] = '%1$s αναφέρθηκε %3$s μέσα σε ένα %8$s.';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s σου έστειλε ένα %8$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s σου έστειλε ένα %8$s.';
$Definition['Activity.DiscussionComment.FullHeadline'] = '%1$s σχολίασε για %4$s %8$s.';
$Definition['Activity.DiscussionComment.ProfileHeadline'] = '%1$s σχολίασε για %4$s %8$s.';
$Definition['Activity.DiscussionMention.FullHeadline'] = '%1$s mentioned %3$s in a %8$s.';
$Definition['Activity.DiscussionMention.ProfileHeadline'] = '%1$s αναφέρθηκε %3$s για %8$s.';
$Definition['Activity.Import.FullHeadline'] = '%1$s εισηγμένα δεδομένα.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s εισηγμένα δεδομένα.';
$Definition['Activity.Join.FullHeadline'] = '%1$s εγγράφηκαν.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s εγγράφηκαν.';
$Definition['Activity.JoinApproved.FullHeadline'] = '%1$s %4$s Η αίτηση μέλους έγινε αποδεκτή.';
$Definition['Activity.JoinApproved.ProfileHeadline'] = '%1$s Η αίτηση μέλους έγινε αποδεκτή.';
$Definition['Activity.JoinCreated.FullHeadline'] = '%3$s έχει δημιουργηθεί λογαριασμός για %1$s.';
$Definition['Activity.JoinCreated.ProfileHeadline'] = '%3$s έχει δημιουργηθεί λογαριασμός για %1$s.';
$Definition['Activity.JoinInvite.FullHeadline'] = '%1$s η αίτηση μέλους έχει γίνει αποδεκτή %4$s .';
$Definition['Activity.JoinInvite.ProfileHeadline'] = '%1$s η αίτηση μέλους έχει γίνει αποδεκτή %4$s.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s άρχισε ένα %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s άρχισε ένα %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s άλλαξε η εικόνα προφίλ %6$s .';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s άλλαξε η εικόνα προφίλ %6$s.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s αλλαγή δικαιωμάτων.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%1$s αλλαγή δικαιωμάτων %4$s.';
$Definition['Activity.SignIn.FullHeadline'] = '%1$s έχει κάνει εγγραφή.';
$Definition['Activity.SignIn.ProfileHeadline'] = '%1$s έχει κάνει εγγραφή.';
$Definition['Activity.WallComment.FullHeadline'] = '%1$s έγραψε πάνω %5$s.';
$Definition['Activity.WallComment.ProfileHeadline'] = '%1$s έγραψε:';
$Definition['Add'] = 'Add';
$Definition['Add Comment'] = 'πρόσθεσε σχόλιο';
$Definition['Add Info &amp; Create Account'] = 'Προσθέστε πληροφορίες &amp; Δημιουργήστε Λογαριασμό.';
$Definition['Add Message'] = 'Προσθέστε μήνυμα';
$Definition['Add People to this Conversation'] = 'Προσθέστε άτομα σε αυτή την συζήτηση.';
$Definition['All Conversations'] = 'Όλες οι συζητήσεις';
$Definition['All Discussions'] = 'Όλες οι συζητήσεις';
$Definition['Allow other members to see your email?'] = 'Επιτρέπετε σε άλλα μέλη να βλέπουν το ηλεκτρονικό ταχυδρομείο σας?';
$Definition['Announce'] = 'Σας ανακοινώνω';
$Definition['Applicants'] = 'Σας ανακοινώνω';
$Definition['Apply'] = 'Εφαρμογή';
$Definition['Apply for Membership'] = 'Εφαρμογή για Μέλη';
$Definition['Are you sure you want to do that?'] = 'Είστε σίγουρος οτι θέλετε να προχωρήσετε?';
$Definition['at'] = 'στο';

$Definition['Back to Discussions'] = 'Πίσω στις συζητήσεις';
$Definition['Bookmark'] = 'σελιδοδείκτης';
$Definition['bookmarked discussion'] = 'Συζήτηση αγαπημένων';
$Definition['Bookmarked Discussions'] = 'Bookmarked Discussions';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'Ανεβάζοντας ένα αρχείο πιστοποιήτε ότι έχετε το δικαίωμα να διανείμετε αυτή την εικόνα και δεν παραβιάζει τους όρους της υπηρεσίας..';

$Definition['Cancel'] = 'ακύρωση';
$Definition['Categories'] = 'Κατηγορίες';
$Definition['Category'] = 'Κατηγορία';
$Definition['Change My Password'] = 'αλλαγή κωδικού πρόσβασης';
$Definition['Change My Picture'] = 'αλλαγή της εικόνας μου';
$Definition['Close'] = 'κλείνω';
$Definition['comment'] = 'σχόλιο';
$Definition['Comment'] = 'σχόλιο';
$Definition['Confirm'] = 'επιβεβαίωση';
$Definition['Confirm Password'] = 'επιβεβαίωση κωδικού πρόσβασης';
$Definition['Connect'] = 'σύνδεση';
$Definition['conversation'] = 'συζήτηση';
$Definition['Conversations'] = 'συζητήσεις';
$Definition['Create One.'] = 'Δημιουργήστε ενα.';

$Definition['Dashboard'] = 'Ταμπλό';
$Definition['Date.DefaultDayFormat'] = '%B %e';
$Definition['Date.DefaultFormat'] = '%B %e, %Y';
$Definition['Date.DefaultTimeFormat'] = '%l:%M%p';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'Διαγραφή';
$Definition['Delete Account'] = 'Διαγραφή Λογαριασμού';
$Definition['Delete Conversation'] = 'Διαγραφή Συνομιλίας';
$Definition['Delete Discussion'] = 'διαγραφή συζήτησης';
$Definition['discussion'] = 'συζήτηση';
$Definition['Discussion Title'] = 'τίτλος Συζήτησης';
$Definition['Discussions'] = 'Συζητήσεις';
$Definition['Don\'t have an account? %s'] = 'Δέν έχετε λογαριασμό? %s';
$Definition['dot'] = 'Τελεία';
$Definition['Draft saved at %s'] = 'Αποθήκευση σχεδίου σαν %s';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = '.';

$Definition['Edit'] = 'Αναπροσαρμογή';
$Definition['Edit Account'] = 'Αναπροσαρμογή Λογαριασμού';
$Definition['Edit My Account'] = 'Αναπροσαρμογή του λογαριασμού μου';
$Definition['Edit My Thumbnail'] = 'Αναπροσαρμογή μικρών εικονιδίων';
$Definition['Edit Preferences'] = 'Eκδοση προτιμήσεων';
$Definition['Email'] = 'ηλεκτρονικό ταχυδρομείο';
$Definition['Email Notifications'] = 'κοινοποιήσεις ηλεκτρονικού ταχυδρομείου';
$Definition['Email Unavailable'] = 'ηλ. ταχυδρομείο μή διαθέσιμο.';
$Definition['EmailHeader'] = 'Γειά σου {Όνομα χρήστη}!
';
$Definition['EmailFooter'] = '
Να έχεις μια υπέροχη μέρα!';

$Definition['EmailInvitation'] = 'Γειά!

%1$s σας προσκαλεί να συμμετάσχετε %2$s. εαν θέλετε να συμμετάσχετε, απλώς πατήστε στον ακόλουθο σύνδεσμο:

  %3$s';
$Definition['EmailMembershipApproved'] = 'Γειά %1$s,

Έχετε εγκριθεί σαν μέλος. Πατήστε πάνω τώρα στον ακόλουθο σύνδεσμο:

  %2$s';
$Definition['EmailWelcome'] = '%2$s έχει δημιουργήσει ένα λογαριασμό για εσάς %3$s. τα αρχικά του :

  Email: %6$s
  Password: %5$s
  Url: %4$s';
$Definition['EmailPassword'] = '%2$s έχει μηδενίσει τους κωδικούς πρόσβασης σας at %3$s. Τα αρχικά σύνδεσης σας τώρα είναι τα ακόλουθα:

  Email: %6$s
  Password: %5$s
  Url: %4$s';
$Definition['EmailConfirmEmail'] = 'Πρέπει να επαληθεύσετε την ηλεκτρονική σας διεύθυνση έτσι ώστε να συνεχίσετε.Παρακαλώ επαληθεύσετε την ηλεκτρονική σας διεύθυνση πατώντας στον ακόλουθο σύνδεσμο: {/entry/emailconfirm,url,domain}/{User.UserID,rawurlencode}/{EmailKey,rawurlencode}';
$Definition['EmailWelcomeRegister'] = 'η εγγραφή σας για τον λογαριασμό (Τίτλος) έχει γίνει με επιτυχία. Οι πληροφορίες σας είναι οι ακόλουθες:

  Όνομα Χρήστη: {User.Name}
  Ηλεκτρονική Διεύθυνση: {User.Email}

Μπορείτε να έχετε πρόσβαση στο δίκτυο με τον εξής τρόπο {/,url,domain}.';
$Definition['EmailWelcomeConnect'] = 'έχετε ενωθεί επιτυχώς με {Tίτλος}. Οι πληροφορίες σας είναι οι ακόλουθες:

  Όνομα Χρήστη: {User.Name}
  Όνομα παροχέα: {ProviderName}

Μπορείτε να έχετε πρόσβαση στο δύκτιο με τον εξής τρόπο {/,url,domain}.';
$Definition['PasswordRequest'] = 'Κάποιος έχει αιτηθεί να μηδενίσει τον κωδικό πρόσβασης σας σε %2$s. για να μηδενίσετε τον κωδικό πρόσβασης σας, ακολουθήστε τον ακόλουθο σύνδεσμο:

  %3$s

Εάν δεν έχετε θέσει αυτό το αίτημα παρακαλω όπως αγνοήσετε το παρόν μήνυμα.';
$Definition['EmailNotification'] = '%1$s

Πατήστε πάνω στον ακόλουθο σύνδεσμο για να το ελέγξετε:
%2$s

Να έχετε μια υπέροχη μέρα!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Πατήστε πάνω στον ακόλουθο σύνδεσμο για να το ελέγξετε:
%2$s

Να έχετε μια υπέροχη μέρα!';
$Definition['Enter the email address of the person you would like to invite:'] = 'Παρακαλώ καταχωρήστε την ηλ. διεύθυνση του ατόμου που θα θέλατε να προσκαλέσετε:';
$Definition['Enter your Email address'] = 'Καταχωρήστε την ηλεκτρ. διεύθυνση';
$Definition['Enter your existing account password.'] = 'Καταχωρήστε το παρόν κωδικό πρόσβασης του λογαριασμού σας.';
$Definition['ErrorCredentials'] = 'Απολογούμαστε, δεν βρέθηκε λογαριασμός που να συσχετίζεται με την ηλ. διεύθυνση και κωδικό πρόσβασης που έχετε καταχωρήσει. Sorry, no account could be found related to the email and password you entered.';
$Definition['ErrorPermission'] = 'Sorry, permission denied.'; 'Απολογούμαστε, αδύνατη πρόσβαση';
$Definition['ErrorRecordNotFound'] = 'Το αρχείο που ζητήθηκε δεν βρέθηκε';
$Definition['ErrorTermsOfService'] = 'Πρέπει να συμφωνήσετε με τους όρους της υπηρεσίας';

$Definition['Female'] = 'θηλυκό';
$Definition['Forgot?'] = 'ξεχάσατε?';

$Definition['Gender'] = 'Φύλο';
$Definition['GenderSuffix.First.f'] = '';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.f'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Πήγαινε';
$Definition['GuestModule.Message'] = 'It looks like you\'re new here. If you want to get involved, click one of these buttons!'; 'Φαίνεται ότι είστε νέος χρήστης εδώ. Εαν επιθυμείτε να ενταχθείτε, πατήστε ένα απο τα παρακάω κουμπιά';

$Definition['he'] = 'αυτός';
$Definition['her'] = 'αυτή';
$Definition['his'] = 'αυτού';
$Definition['Howdy, Stranger!'] = 'γειά σου ξένε!';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>';
$Definition['I remember now!'] = 'Τώρα θυμήθηκα!';
$Definition['In this Conversation'] = 'Σε αυτή τη συζήτηση';
$Definition['Inbox'] = 'εισερχόμενο';
$Definition['Internal'] = 'εσωτερικό';
$Definition['Invitation Code'] = 'Κωδικός πρόσκλησης';
$Definition['Invite'] = 'Πρόσκληση';
$Definition['Invited by'] = 'Πρόσκληση από';

$Definition['Joined'] = 'Ένταξη';

$Definition['Keep me signed in'] = 'Διατήρηση σύνδεσης';

$Definition['Last Active'] = 'Τελευταία επίσκεψη';
$Definition['Login with Facebook'] = 'σύνδεση απο Facebook';

$Definition['Male'] = 'Male';
$Definition['Most recent by %1$s'] = 'Πιο πρόσφατα από %1$s';
$Definition['My Bookmarks'] = 'Τα αποθηκευμένα μου';
$Definition['My Discussions'] = 'Οι συζητήσεις μου';
$Definition['My Drafts'] = 'Τα προσχέδια μου';
$Definition['My Invitations'] = 'Οι προσκλήσεις μου';
$Definition['My Preferences'] = 'Οι προτιμήσεις';

$Definition['Name Unavailable'] = 'Μη διαθέσιμο όνομα';
$Definition['No discussions were found.'] = 'Δεν βρέθηκαν συζητήσεις .';
$Definition['Notifications'] = 'Γνωστοποίηση';
$Definition['Notify me of private messages.'] = 'Ειδοποίησε με με προσωπικό μήνυμα.';
$Definition['Notify me when I am added to private conversations.'] = 'Ενημερώστε με όταν με προσθέτουν σε προσωπικές συζητήσεις.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'Ενημερώστε με όταν άτομα σχολιάζουν τις αγαπημένες μου συζητήσεις.';
$Definition['Notify me when people comment on my discussions.'] = 'Ενημερώστε με όταν άτομα σχολιάζουν συζητήσεις δικές μου.';
$Definition['Notify me when people mention me in comments.'] = 'Ενημερώστε με όταν άτομα με συμπεριλαμβάνουν σε σχόλια.';
$Definition['Notify me when people mention me in discussion titles.'] = 'Ενημερώστε με όταν άτομα με αναφέρουν σε τίτλους συζητήσεων.';
$Definition['Notify me when people reply to my wall comments.'] = 'Ενημερώστε με όταν άτομα απαντούν σε σχόλια πάνω στον τοίχο μου.';
$Definition['Notify me when people write on my wall.'] = 'Ενημερώστε με όταν άτομα γράφουν πάνω στον τοίχο μου.';

$Definition['Okay'] = 'Εντάξει';
$Definition['On'] = 'Πάνω';
$Definition['Options'] = 'Επιλογές';
$Definition['Or you can...'] = 'Η ακόμα μπορείς';
$Definition['Original'] = 'Αρχικό';

$Definition['PageDetailsMessage'] = '%1$s to %2$s';
$Definition['PageDetailsMessageFull'] = '%1$s to %2$s of %3$s';
$Definition['Password'] = 'Κωδικός πρόσβασης';
$Definition['PasswordRequest'] = 'Γειά %1$s,

Someone has requested to reset your password at %2$s. To reset your password, follow this link:
%3$s 

If you did not make this request, disregard this email.';
$Definition['Passwords don\'t match'] = 'Οι κωδικοί πρόσβασης δεν είναι αποδεκτοί';
$Definition['Permalink'] = 'Permalink';
$Definition['Please wait while you are redirected. If you are not redirected, click <a href="%s">here</a>.'] = 'Παρακαλώ περιμένετε ενώ κατευθύνεστε ξανά. εαν δεν σας κατευθύνει ξανά πατήστε εδώ <a href="%s">here</a>.';
$Definition['Post Comment'] = 'τοποθετήστε σχόλιο';
$Definition['Post Discussion'] = 'τοποθετήστε συζήτηση';
$Definition['Powered by Vanilla'] = 'Τροφοδότηση από Βανίλλια';
$Definition['Preview'] = 'Προεπισκόπηση';
$Definition['Profile Picture'] = 'φωτογραφία προφίλ';

$Definition['Recent Activity'] = 'Τελευταία ενέργεια';
$Definition['Recipients'] = 'αποδέκτες';
$Definition['Redirecting...'] = 'Ανακατεύθυνση...';
$Definition['Remember me on this computer'] = 'Να με θυμάστε σε αυτό τον υπολογιστή';
$Definition['Remove My Picture'] = 'αφαίρεση εικόνας';
$Definition['Request a new password'] = 'Αίτημα νέου κωδικού πρόσβασης';
$Definition['Roles'] = 'Ρόλοι';

$Definition['Save'] = 'Αποθήκευση';
$Definition['Save Draft'] = 'αποθήκευση προσχεδίου';
$Definition['Save Preferences'] = 'αποθήκευση προτιμήσεων';
$Definition['Search'] = 'Έρευνα';
$Definition['Select an image on your computer (2mb max)'] = 'διαλέξτε μια εικόνα απο τον υπολογιστή σας (2mb max)';
$Definition['Send %s a Message'] = 'Αποστολή σαν μήνυμα';
$Definition['Send Message'] = 'Αποστολή μηνύματος';
$Definition['Sent To'] = 'Αποστολή σε';
$Definition['Share'] = 'Κοινοποίηση';
$Definition['she'] = 'αυτη';
$Definition['Sign Up'] = 'εγγραφείτε';
$Definition['Sink'] = 'νεροχύτης/βυθίζομαι';
$Definition['somebody'] = 'κάποιος';
$Definition['Start a New Conversation'] = 'Άρχισε μια καινούργια συνομιλία';
$Definition['Start a New Discussion'] = 'άρχισε μια καινούργια συζήτηση';
$Definition['Start Conversation'] = 'Άρχισε συνομιλία';
$Definition['Started by %1$s'] = 'άρχισε από %1$s';
$Definition['Status'] = 'Κατάσταση';

$Definition['Thank You!'] = 'Ευχαριστώ!';
$Definition['Thumbnail'] = 'Thumbnail';
$Definition['Transport error: %s'] = 'A fatal error occurred while processing the request.<br />The server returned the following response: %s';

$Definition['Unbookmark'] = 'Unbookmark';
$Definition['Upload'] = 'Upload';
$Definition['Username'] = 'Όνομα χρήστη';

$Definition['ValidateBoolean'] = '%s Δεν είναι συμβατό boolean';
$Definition['ValidateConnection'] = 'The connection parameters you specified failed to open a connection to the database. The database reported the following error: <code>%s</code> ';
$Definition['ValidateDate'] = '%s  Δεν είναι έγκυρη ημερομηνία';
$Definition['ValidateDecimal'] = '%s  Δεν είναι έγκυρος δεκαδικός';
$Definition['ValidateEmail'] = '%s Εμφανίζεται να μην είναι έγκυρο';
$Definition['ValidateEnum'] = '%s Δεν είναι έγκυρο';
$Definition['ValidateInteger'] = '%s  δεν είναι έγκυρος ακαίρεος αριθμός';
$Definition['ValidateLength'] = '%1$s is %2$s Πολύ μεγάλοι χαρακτήρες';
$Definition['ValidateMatch'] = '%s Δεν ταιριάζουν τα πεδία';
$Definition['ValidateMinimumAge'] = 'Πρέπει να είστε 16 ετών και άνω για να συνεχίσετε';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Πρέπει να επιλέξετε τουλάχιστον ένα %s';
$Definition['ValidateRegex'] = '%s  φαίνεται να μην είνα στη σωστή μορφή';
$Definition['ValidateRequired'] = '%s  απαιτείται';
$Definition['ValidateRequiredArray'] = 'You must select at least one %s.';
$Definition['ValidateTime'] = '%s Δεν είναι έγκυρος χρόνος';
$Definition['ValidateTimestamp'] = '%s Δεν είναι έγκυρο timestamp';
$Definition['ValidateUsername'] = 'Usernames must be 3-20 characters and consist of letters, numbers, and underscores.';
$Definition['ValidateVersion'] = 'The %s field is not a valid version number. See the php version_compare() function for examples of valid version numbers.';
$Definition['Visits'] = 'επισκέπτεται';

$Definition['wall'] = 'τοίχος';
$Definition['Why do you want to join?'] = 'Γιατι θέλετε να ενταχθείτε?';
$Definition['Write a comment'] = 'Γράψετε ένα σχόλιο';
$Definition['Write Comment'] = 'Γράψετε ένα σχόλιο';
$Definition['Write something about yourself...'] = 'γράψετε κάτι για τον εαυτό σας...';

$Definition['you'] = 'εσύ';
$Definition['You'] = 'εσύ';
$Definition['You already have an account here.'] = 'Ήδη έχετε λογαριασμό μαζί μας.';
$Definition['You are connected as %s through %s.'] = 'Είστε συνδεδεμένος διαμέσου.';
$Definition['You do not have any conversations.'] = 'Δεν έχετε συνομιλίες.';
$Definition['You do not have any notifications yet.'] = 'Ακόμη δεν έχετε συνομιλίες.';
$Definition['your'] = 'your';
$Definition['Your application will be reviewed by an administrator. You will be notified by email if your application is approved.'] = 'η αίτηση σας θα αναθεωρηθεί απο τον διαχειριστή.';
$Definition['Your registered username: <strong>%s</strong>'] = 'Το εγκεγραμένο σας όνομα χρήστη: <strong>%s</strong>';

$Definition['Save Comment'] = 'αποθήκευση σχολίου';
$Definition['Unannounce'] = 'Απο-ανακοινώνω';
$Definition['Announcement'] = 'ανακοίνωση';
$Definition['Dismiss'] = 'απόρριψη';
$Definition['Closed'] = 'κλειστό' ;
$Definition['Reopen'] = 'Ξαναανοίγω'; //'παλιός κωδικός σύνδεσης';
$Definition['New Password'] = 'Nέος κωδικός σύνδεσης';
$Definition['Change Password'] = 'αλλαγή κωδικού σύνδεσης';
$Definition['Add a Comment'] = 'Προσθέστε σχόλιο';
$Definition['Edit Discussion'] = 'αναθεώρηση συζήτησης';
$Definition['Uninvite'] = 'Uninvite';
$Definition['Send Again'] = 'αποστολή ξανά';
$Definition['Pending'] = 'εκκρεμεί';
