<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2011-02-08 04:31:50 **/

//$Definition['Garden.Messages.Location.[Base]'] = 'Toutes les Pages';

$Definition['%1$s Version %2$s'] = '%1$s Version %2$s';

$Definition['<General Error>'] = '<Erreur Générale>';

$Definition['_Locale'] = 'Pack de Langue';

$Definition['%s level'] = '%s niveau';
$Definition['%s levels'] = '%s niveaux';
$Definition['more than %s deep'] = 'plus de %s de profondeur';
$Definition['%1$s on %2$s'] = '%1$s sur %2$s';
$Definition['%1$s Version %2$s'] = '%1$s Version %2$s';
$Definition['%s user(s) found.'] = '%s utilisateur(s) trouvé(s).';
$Definition['more than %s levels deep'] = 'plus de %s niveaux de profondeur';

$Definition['<input type="file" id="Form_ImportFile" name="ImportFile" value="" />'] = '<input type="file" id="Form_ImportFile" name="ImportFile" value="" />';

$Definition['@Require users to confirm their email addresses (recommended)'] = 'Demander aux utilisateurs de confirmer leur adresse email (recommandé)';

$Definition['(YYYY-mm-dd)'] = '(YYYY-mm-dd)';

$Definition['1 month after being sent'] = '1 mois après avoir été envoyé';
$Definition['1 week after being sent'] = '1 semaine après avoir été envoyé';

$Definition['2 weeks after being sent'] = '2 semaines après avoir été envoyé';

$Definition['<strong>The basic registration form requires</strong> that new users copy text from a "Captcha" image to keep spammers out of the site. You need an account at <a href="http://recaptcha.net/">recaptcha.net</a>. Signing up is FREE and easy. Once you have signed up, come back here and enter the following settings:'] = '<strong>Le formulaire d\'inscription par défaut</strong> demande aux nouveaux utilisateurs de recopier le texte contenu dans une image "Captcha" image pour garder les spammeurs hors du site. Vous devez avoir préalablement créé un compte sur <a href="http://recaptcha.net/">recaptcha.net</a>. L\'inscription est GRATUITE et facile. Une fois que vous vous êtes inscrit, revenez ci et entrez les paramètres suivants :';

// Tableau de bord Vanilla
$Definition['Above Main Content'] = 'Au-dessus du Contenu Principal';
$Definition['Activate'] = 'Activer';
$Definition['Active Users'] = 'Utilisateurs Actifs';
$Definition['Activity'] = 'Activité';
$Definition['Add'] = 'Ajouter';
$Definition['Add Category'] = 'Ajouter une Catégorie';
$Definition['Add Item'] = 'Ajouter un Élément';
$Definition['Add Message'] = 'Rédiger un Message';
$Definition['Add Role'] = 'Ajouter un Statut';
$Definition['Add Route'] = 'Ajouter une Redirection';
$Definition['Add User'] = 'Ajouter un Utilisateur';
$Definition['Added By'] = 'Ajouté par';
$Definition['Adding & Editing Categories'] = 'Ajouter & Modifier des Catégories';
$Definition['Addons'] = 'Modules';
$Definition['Administrator'] = 'Administrateur';
$Definition['Adresse email visible par les autres utilisateurs.'] = 'Adresse email visible par les autres utilisateurs.';
$Definition['Advanced'] = 'Avancé';
$Definition['AdvancedNotifications'] = 'Notifications Avancées';
$Definition['Advanced Options'] = 'Options Avancées';
$Definition['Advanced Forum Settings'] = 'Paramètres Avancés du Forum';
$Definition['All'] = 'Toutes';
$Definition['All %1$s'] = 'Toutes %1$s';
$Definition['All Categories'] = 'Toutes les Catégories';
$Definition['All Dashboard Pages'] = 'Toutes les Pages du Tableau de bord';
$Definition['All Discussions'] = 'Toutes les Discussions';
$Definition['All Forum Pages'] = 'Toutes les Pages du Forum';
$Definition['All Pages'] = 'Toutes les Pages';
$Definition['Allow'] = 'Autoriser';
$Definition['Allow users to dismiss this message'] = 'Autoriser les utilisateurs à désactiver ce message.';
$Definition['API Status'] = 'Statut de l\'API';
$Definition['Appearance'] = 'Apparence';
$Definition['Applicant'] = 'Candidat';
$Definition['Applicants'] = 'Candidats';
$Definition['Application'] = 'Application';
$Definition['ApplicationHelp'] = 'Les Applications vous permettent d\'ajouter de nombreuses fonctionnalités à votre forum Vanilla.<br />
Une fois qu\'une application a été ajoutée à votre dossier %s, vous pouvez l\'activer ou la désactiver ici.';
$Definition['Applications'] = 'Applications';
$Definition['Applied On'] = 'Date';
$Definition['Apply'] = 'Appliquer';
$Definition['Approval'] = 'Approbation';
$Definition['Approve'] = 'Accepter';
$Definition['Archive Discussions'] = 'Archiver des Discussions';
$Definition['Are you sure you want to delete this category?'] = 'Êtes-vous sûr de vouloir supprimer cette catégorie ?';
$Definition['Are you sure you want to do that?'] = 'Êtes-vous sûr de vouloir faire cela ?';
$Definition['at'] = 'at';
$Definition['Authentication'] = 'Authentification';
$Definition['Authors can always edit their posts'] = 'Les auteurs peuvent toujours éditer leurs publications';
$Definition['Authors can edit for 1 day after posting'] = 'Les auteurs peuvent éditer leurs publications 1 jour après';
$Definition['Authors can edit for 1 month after posting'] = 'Les auteurs peuvent éditer leurs publications 1 mois après';
$Definition['Authors can edit for 1 week after posting'] = 'Les auteurs peuvent éditer leurs publications 1 semaine après';
$Definition['Authors can edit for 15 minutes after posting'] = 'Les auteurs peuvent éditer leurs publications 15 minutes après';
$Definition['Authors can edit for 30 minutes after posting'] = 'Les auteurs peuvent éditer leurs publications 30 minutes après';
$Definition['Authors can edit for 5 minutes after posting'] = 'Les auteurs peuvent éditer leurs publications 5 minutes après';
$Definition['Authors cannot edit their posts'] = 'Les auteurs ne peuvent pas modifier leurs publications';

$Definition['Ban Item'] = 'Élément';
$Definition['Ban List'] = 'Liste Noire';
$Definition['Ban Type'] = 'Type de Bannissement';
$Definition['BanType'] = $Definition['Ban Type'];
$Definition['Ban Value'] = 'Valeur de Bannissement';
$Definition['Blocked'] = 'Bloqués';
$Definition['Banned'] = 'Bannis';
$Definition['Banner'] = 'Bandeau';
$Definition['Banner Logo'] = 'Logo du Bandeau';
$Definition['Banner Title'] = 'Titre du Bandeau';
$Definition['Basic'] = 'Par défaut';
$Definition['Below Sidebar'] = 'En-dessous de la barre de navigation latérale';
$Definition['Browse for a new banner logo if you would like to change it:'] = 'Téléchargez un nouveau logo si vous souhaitez en changer :';
$Definition['By %s'] = 'Par %s';

$Definition['Cancel'] = 'Annuler';
$Definition['Categories'] = 'Catégories';
$Definition['Category to Use'] = 'Catégorie à Utiliser';
$Definition['Categories &amp; Discussions'] = 'Catégories & Discussions';
$Definition['Categories are used to help organize discussions.'] = 'Les catégories sont utilisées pour aider à organiser les Discussions. Glissez-Déposez les catégories pour les classer et les imbriquer.';
$Definition['Categories are used to organize discussions.'] = 'Les <strong>Catégories</strong> vous permettent d\'organiser les discussions.';
$Definition['Category'] = 'Catégorie';
$Definition['Category Management'] = 'Gestion des Catégories';
$Definition['Category Page Layout'] = 'Mise en Page des Catégories';
$Definition['Category Url:'] = 'URL de la catégorie :';
$Definition['Change the look of All Categories'] = 'Vous pouvez modifier l\'aspect de la page <b>Toutes les Catégories</b> <a href="%s">ici</a>.';
$Definition['Change the way that new users register with the site.'] = 'Changez la manière dont les nouveaux utilisateurs s\'inscrivent dans la communauté.';
$Definition['Changing the Discussions Menu Link'] = 'Changer le lien du menu Discussions';
$Definition['Check all permissions that apply for each role'] = 'Choisissez toutes les autorisations qui s\'appliquent à chaque statut';
$Definition['Check all permissions that apply to this role:'] = 'Vérifiez toutes les autorisations qui s\'appliquent à ce statut :';
$Definition['Check all roles that apply to this user:'] = 'Cochez tous les statuts qui s\'appliquent à cet utilisateur.';
$Definition['Choose and configure your forum\'s authentication scheme.'] = 'Choisissez et configurez la méthode d\'authentification de votre communauté.';
$Definition['Choose how to handle all of the content associated with the user account for %s (comments, messages, etc).'] = 'Choisissez la manière de gérer tout le contenu associé au compte utilisateur <i>%s</i> (commentaires, messages, etc).';
$Definition['Choose who can send out invitations to new members:'] = 'Choisissez qui peut envoyer des invitations à de nouveaux membres :';
$Definition['Close'] = 'Fermer';
$Definition['comment(s)'] = 'commentaire(s)';
$Definition['Comments'] = 'Commentaires';
$Definition['Comments Page'] = 'Les Pages de Commentaires';
$Definition['Comments per Page'] = 'Commentaires par Page';
$Definition['Configure an Authenticator'] = 'Configurer une méthode d\'authentification';
$Definition['Configure how nested categories are displayed to users.'] = 'Configurez la façon dont les catégories imbriquées sont affichées aux utilisateurs.';
$Definition['Configuring Vanilla\'s Homepage'] = 'Configurer la Page d\'accueil de la Communauté Vanilla';
$Definition['Confirm'] = 'Confirmer';
$Definition['Confirm Email'] = 'Confirmation Email';
$Definition['Confirm email addresses'] = 'Demander aux utilisateurs de confirmer leurs adresses e-mail (recommandé)';
$Definition['Create Discussions'] = 'Créer des Discussions';

$Definition['Copy'] = 'Copier';
$Definition['Current Authenticator'] = 'Méthode d\'authentification actuelle';
$Definition['Current Theme'] = 'Thème actuel';

$Definition['Dashboard'] = 'Tableau de bord';
$Definition['Dashboard Home'] = 'L\'accueil du Tableau de bord';
$Definition['Dashboard Summaries'] = 'Résumés du Tableau de bord';
$Definition['Default %s Permissions'] = 'Droits d\'accès de %s par défaut';
$Definition['Default Category Permissions'] = 'Autorisations des Catégories par défaut';
$Definition['Default Locale'] = 'Pack de Langue par défaut';
$Definition['Delete'] = 'Supprimer';
$Definition['Delete Category'] = 'Supprimer une Catégorie';
$Definition['Delete Forever'] = 'Supprimer Définitivement';
$Definition['Delete the user and all of the user\'s content. This will cause discussions to be disjointed, appearing as though people are responding to content that is not there. This is a great option for removing spammer content.'] = 'Supprimer l\'utilisateur ainsi que tout le contenu qu\'il a publié. Cela pourrait générer des discussions décousues, apparaissant comme si des utilisateurs répondaient à du contenu qui n\'existe pas. Cependant, c\'est une bonne option pour supprimer du contenu indésirable (spam).';
$Definition['Delete the user, but just replace all of the user\'s content with a message stating the user has been deleted. This will give other users a visual cue that there is missing information so they better understand how a discussion might have flowed before the deletion.'] = 'Supprime l\'utilisateur, mais remplace tout le contenu de l\'utilisateur par un message indiquant que l\'utilisateur a été supprimé. Ceci donnera aux autres utilisateurs une information visuelle indiquant qu\'il manque du contenu : il comprendront ainsi mieux comment une discussion a pu se dérouler avant sa suppression.';
$Definition['Delete User'] = 'Supprimer l\'Utilisateur';
$Definition['Delete User Content'] = 'Supprimer le Contenu de l\'Utilisateur';
$Definition['Delete User: %s'] = 'Supprimer l\'Utilisateur : %s';
$Definition['Description'] = 'Description';
$Definition['Did You Know?'] = 'Le saviez-vous ?';
$Definition['Disable'] = 'Désactiver';
$Definition['Disabled'] = 'Désactivées';
$Definition['Disabled %1$s'] = 'Désactivées %1$s';
$Definition['Discussion & Comment Editing'] = 'Modification des Discussions & Commentaires';
$Definition['Discussions Page'] = 'Les Pages des Discussions';
$Definition['discussion(s)'] = 'discussion(s)';
$Definition['Discussions'] = 'Discussions';
$Definition['Discussions per Page'] = 'Discussions par Page';
$Definition['Dismiss'] = 'Rejeter';
$Definition['Display root categories as headings.'] = 'Afficher les catégories de base en tant que titres.';
$Definition['Do not display the categories in the side panel.'] = 'Ne pas afficher les catégories dans la barre de navigation latérale.';
$Definition['Don\'t Refresh'] = 'Ne pas actualiser';
$Definition['Don\'t use Categories'] = 'Ne pas utiliser les Catégories';
$Definition['dot'] = 'dot';
$Definition['Drag and drop the categories below to sort and nest them.'] = 'Glissez-Déposez les catégories ci-dessous pour les trier et les imbriquer.';
$Definition['Droits d\'accès de Catégorie par défaut'] = 'Droits d\'accès de Catégorie par défaut';

$Definition['Edit'] = 'Modifier';
$Definition['edit'] = 'modifier';
$Definition['Edit/Delete Log'] = 'Modifier/Effacer les Logs';
$Definition['Edit Category'] = 'Modifier la Catégorie';
$Definition['Edit Message'] = 'Modifier le Message';
$Definition['Edit Role'] = 'Modifier le Statut';
$Definition['Edit Route'] = 'Modifier la Redirection';
$Definition['Edit User'] = 'Modifier l\'Utilisateur';
$Definition['EditContentTimeout.Notes'] = 'Note: Si un utilisateur a l\'autorisation de modifier du contenu, ces autorisations prévaudront sur toutes celles qui seront sélectionnées ici.';
$Definition['Email'] = 'Email';
$Definition['Email Confirmation Role'] = 'Statut de Confirmation d\'adresse Email';
$Definition['Email sent from the application will be addressed from the following name and address'] = 'Les emails envoyés à partir de l\'application seront adressés de la part du nom et de l\'adresse ci-dessous';
$Definition['Email visible to other users'] = 'Adresse email visible par les autres utilisateurs.';
$Definition['Enable'] = 'Activer';
$Definition['Enable this message'] = 'Activer ce message';
$Definition['Enabled'] = 'Activées';
$Definition['Enabled %1$s'] = 'Activées %1$s';
$Definition['Enabling a Locale Pack'] = 'Activer un Pack de Langue';
$Definition['Enter the url to the page you would like to use as your homepage:'] = 'Entrez l\'url que vous souhaitez utiliser en tant que page d\'accueil :';
$Definition['Erase User Content'] = 'Effacer le Contenu de l\'Utilisateur';
$Definition['Every 1 minute'] = 'Toutes les minutes';
$Definition['Every 10 seconds'] = 'Toutes les 10 secondes';
$Definition['Every 30 seconds'] = 'Toutes les 30 secondes';
$Definition['Every 5 minutes'] = 'Toutes les 5 minutes';
$Definition['Every 5 seconds'] = 'Toutes les 5 secondes';
$Definition['Every Page'] = 'Toutes les Pages';
$Definition['Exclude archived discussions from the discussions list'] = 'Exclure les discussions archivées de la liste des discussions';
$Definition['Existing members send invitations to new members.'] = 'Les membres existants envoient des invitations aux nouveaux membres.';

$Definition['First Visit'] = '1ère visite';
$Definition['Flood Control'] = 'Contrôle des Flux';
$Definition['Follows'] = 'Suivies';
$Definition['Forum'] = 'Forum';
$Definition['Forum Settings'] = 'Paramètres du Forum';

$Definition['Garden'] = 'Forum';
$Definition['Garden.Import.Description'] = 'Utilisez cette page pour importer les données d\'un autre forum qui a été exporté en utilisant l\'exportateur de Vanilla. Pour plus d\'informations <a href="%s">consultez la documentation sur l\'importation</a>.';
$Definition['Garden.Import.InputInstructions'] = 'Entrez l\'email et le mot de passe de l\'utilisateur administrateur des données importées.';
$Definition['Garden.Import.Overwrite.Description'] = 'Avertissement: Toutes les données de ce forum seront écrasées.';
$Definition['Generate'] = 'Genérer';
$Definition['Generate import SQL only'] = 'Générer des imports SQL uniquement';
$Definition['Generate Password'] = 'Générer un Mot de passe';
$Definition['Get More Applications'] = 'Obtenir plus d\'applications';
$Definition['Get more information on creating custom routes'] = 'Plus d\'informations sur la création de Redirections personnalisées';
$Definition['Get More Plugins'] = 'Obtenir plus d\'extensions';
$Definition['Get More Themes'] = 'Obtenir plus de thèmes';
$Definition['Go'] = 'Ok';
$Definition['Guest'] = 'Invité';

$Definition['Heads Up! This is a special role that does not allow active sessions. For this reason, the permission options have been limited to "view" permissions.'] = 'Attention ! Ceci est un statut particulier qui n\'autorise pas de sessions actives. Pour cette raison, les options d\'autorisation ont été limitées à la seule fonction "visualisation".';
$Definition['here'] = 'ici';
$Definition['Homepage'] = 'Page d\'accueil';

$Definition['Import'] = 'Importer';
$Definition['Importing to Vanilla'] = 'Importer vers Vanilla';
$Definition['Inbox'] = 'Boîte de Réception';
$Definition['Information'] = 'Information';
$Definition['Internal'] = 'Interne';
$Definition['Internaltionalization & Localization'] = 'Internaltionalisation & Localisation';
$Definition['Invitation'] = 'Invitation';
$Definition['Invitations can be sent from users\' profile pages.'] = 'Lorsque vous utilisez la méthode d\'inscription par invitation, les utilisateurs auront un lien nommé <a href="%s" class="Popup">Mes Invitations</a> sur leurs pages de profil.';
$Definition['Invitations per month'] = 'Invitations par mois';
$Definition['Invitations will expire'] = 'Les invitations expireront';
$Definition['Invité'] = 'Invité';
$Definition['IP Address'] = 'Adresse IP';
$Definition['It is a good idea to keep the maximum number of characters allowed in a comment down to a reasonable size.'] = 'Il est conseillé de maintenir le nombre maximum de caractères autorisés dans un commentaire à une taille raisonnable tirant vers le bas.';

$Definition['Just delete the user record, and keep all of the user\'s content.'] = 'Efface simplement les données de l\'utilisateur, et conserve tout le contenu de l\'utilisateur.';

$Definition['Keep User Content'] = 'Conserver le Contenu de l\'Utilisateur';
$Definition['Key Type'] = 'Type de Clé';
$Definition['Key Value'] = 'Valeur de la Clé';

$Definition['Last IP'] = 'Dernière IP';
$Definition['Last Visit'] = 'Dernière Visite';
$Definition['Locales'] = 'Packs de Langues';
$Definition['Locales are in your %s folder.'] = 'Les Packs de Langue vous permettent d\'utiliser plusieurs langues sur votre forum.<br />Une fois qu\'un pack de langue a été déposé dans le dossier %s, vous pouvez l\'activer ou le désactiver ici.';
$Definition['Location'] = 'Emplacement';

$Definition['Make sure you click View Page'] = 'Cliquez sur <a href="%s">Voir la Page</a> pour voir à quoi ressemblera votre page catégories une fois que vous aurez sauvegardé.';
$Definition['Make sure you select at least one item before continuing.'] = 'Sélectionnez au moins un élément avant de continuer.';
$Definition['Manage'] = 'Gérer';
$Definition['Manage Applications'] = 'Gestion des Applications';
$Definition['Manage Categories'] = 'Gestion des Catégories';
$Definition['Manage Messages'] = 'Gestion des Messages';
$Definition['Manage Plugins'] = 'Gestion des Modules complémentaires';
$Definition['Manage Roles & Permissions'] = 'Gestion des Statuts & Autorisations';
$Definition['Manage Routes'] = 'Gestion des Redirections';
$Definition['Manage Spam'] = 'Gestion du Spam';
$Definition['Manage Themes'] = 'Gestion des Thèmes';
$Definition['Manage Users'] = 'Gestion des Utilisateurs';
$Definition['Managing Categories'] = 'Gestion des Catégories';
$Definition['Max Comment Length'] = 'Longueur Maximale des Commentaires';
$Definition['Member'] = 'Membre';
$Definition['Message'] = 'Message';
$Definition['Messages'] = 'Messages';
$Definition['Messages can appear anywhere in your application.'] = 'Les messages peuvent apparaître n\'importe où dans votre application, et peuvent être utilisés pour informer vos utilisateurs des nouvelles et des événements. Utilisez cette page pour réorganiser vos messages en les faisant glisser en haut ou en bas.';
$Definition['Method'] = 'Méthode';
$Definition['minute(s)'] = 'minute(s)';
$Definition['Moderation'] = 'Modération';
$Definition['Moderation Queue'] = 'En attente de Modération';
$Definition['Moderator'] = 'Modérateur';

$Definition['Name'] = 'Nom';
$Definition['Need More Help?'] = 'Besoin d\'aide ?';
$Definition['never'] = 'Jamais';
$Definition['New comments in the last day'] = 'Nouveaux commentaires  ces dernières 24h';
$Definition['New comments in the last week'] = 'Nouveaux commentaires ces 7 derniers jours';
$Definition['New conversations in the last day'] = 'Nouvelles conversations  ces dernières 24h';
$Definition['New conversations in the last week'] = 'Nouvelles conversations ces 7 derniers jours';
$Definition['New discussions in the last day'] = 'Nouvelles discussions ces dernières 24h';
$Definition['New discussions in the last week'] = 'Nouvelles discussions ces 7 derniers jours';
$Definition['New messages in the last day'] = 'Nouveaux messages des dernières 24h';
$Definition['New messages in the last week'] = 'Nouveaux messages des 7 derniers jours';
$Definition['New Password'] = 'Nouveau Mot de passe';
$Definition['New users are only registered through SSO plugins.'] = 'Les nouveaux utilisateurs sont enregistrés uniquement à l\'aide de plugins SSO.';
$Definition['New users are reviewed and approved by an administrator (that\'s you!).'] = 'Les nouveaux utilisateurs sont passés en revue et approuvés par un administrateur (c\'est vous !).';
$Definition['New users fill out a simple form and are granted access immediately.'] = 'Les nouveaux utilisateurs remplissent un simple fomulaire et bénéficient d\'un accès immédiat.';
$Definition['New users in the last day'] = 'Nouveaux utilisateurs ces dernières 24h';
$Definition['New users in the last week'] = 'Nouveaux utilisateurs ces 7 derniers jours';
$Definition['No Items Selected'] = 'Aucun élement sélectionné';
$Definition['None'] = 'Aucun';
$Definition['Not Authorized (401)'] = 'Accès Refusé (401)';
$Definition['Not Found (404)'] = 'Page Introuvable (404)';
$Definition['Not Spam'] = 'Non Spam';
$Definition['Notes'] = 'Remarques';
$Definition['Notify'] = 'Signaler';
$Definition['Number of blocked registrations'] = 'Nombre d\'inscriptions bloquées';

$Definition['OK'] = 'Ok';
$Definition['Okay'] = 'Oui';
$Definition['Only Allow Each User To Post'] = 'Permettre seulement aux utilisateurs de publier';
$Definition['Operation By'] = 'Par';
$Definition['Options'] = 'Options';
$Definition['Or Spamblock For'] = 'Ou bloquer le spam pendant';
$Definition['Organize Categories'] = 'Organiser les Catégories';
$Definition['Other Themes'] = 'Autres Thèmes';
$Definition['Outgoing Email'] = 'Email Sortant';

$Definition['Page'] = 'Page';
$Definition['Page Not Found'] = 'Page Introuvable';
$Definition['Panel Box'] = 'Boîte de dialogue';
$Definition['Password'] = 'Mot de Passe';
$Definition['Password Options'] = 'Options de Mot de passe';
$Definition['Permanent (301)'] = 'Redirection Permanente (301)';
$Definition['Permission.Category'] = 'Catégorie';
$Definition['Please choose an authenticator to configure.'] = 'Veuillez choisir une méthode d\'authentification à configurer.';
$Definition['Plugin'] = 'Extension';
$Definition['PluginHelp'] = 'Les extensions vous permettent d\'ajouter des fonctionnalités à votre site.<br />Une fois qu\'une extension a été ajoutée à votre dossier %s, vous pouvez l\'activer ou la désactiver ici.';
$Definition['Plugins'] = 'Extensions';
$Definition['Popular Discussions'] = 'Discussions Populaires';
$Definition['Position'] = 'Emplacement';
$Definition['Prevent spam on your forum by limiting the number of discussions &amp; comments that users can post within a given period of time.'] = 'Empêchez le Spam sur votre forum en limitant le nombre de discussions et de commentaires que les utilisateurs peuvent publier au cours d\'une période donnée.';
$Definition['Preview'] = 'Aperçu';
$Definition['Private Key'] = 'Clé Privée';
$Definition['Proceed'] = 'Oui, je veux le faire !';
$Definition['Profiles'] = 'Profils';
$Definition['Profile Page'] = 'La Page de Profil';
$Definition['Public Key'] = 'Clé Publique';

$Definition['Quick-Start Guide to Creating Themes for Vanilla'] = 'Guide de démarrage rapide pour la Création de Thèmes pour Vanilla';

$Definition['Recent News'] = 'Actualités Récentes';
$Definition['Recent Tutorials'] = 'Tutoriels Récents';
$Definition['Recently Active Users'] = 'Derniers Utilisateurs Actifs';
$Definition['Record Content'] = 'Contenu';
$Definition['Refresh Comments'] = 'Actualiser les Commentaires';
$Definition['Registration'] = 'Inscription';
$Definition['Remove'] = 'Supprimer';
$Definition['Remove Banner Logo'] = 'Supprimer le logo du Bandeau';
$Definition['Reputation'] = 'Réputation';
$Definition['Requires: '] = 'Requiert : ';
$Definition['Reset Password'] = 'Réinitialisation du Mot de passe';
$Definition['Reset password and send email notification to user'] = 'Réinitialiser le mot de passe et envoyer un courriel à l\'utilisateur.';
$Definition['Restore'] = 'Restaurer';
$Definition['Reveal Password'] = 'Afficher le Mot de passe';
$Definition['Role'] = 'Statut';
$Definition['Role Name'] = 'Nom du Statut';
$Definition['Roles'] = 'Statuts';
$Definition['Roles & Permissions'] = 'Statuts & Autorisations';
$Definition['Roles determine user\'s permissions.'] = 'Chaque utilisateur de votre communauté est associé au moins à un statut. Les Statuts permettent de déterminer ce que les utilisateurs sont autorisés à faire.';
$Definition['Route'] = 'Redirection';
$Definition['Route Expression'] = 'Libellé de la Redirection';
$Definition['Routes'] = 'Redirections';
$Definition['Routes can be used to redirect users to various parts of your site depending on the url.'] = 'Les Redirections peuvent être utilisées pour rediriger les utilisateurs vers différentes parties de votre forum, en fonction de l\'URL.';
$Definition['Réinitialiser le mot de passe et envoyer un courriel à l\'utilisateur.'] = 'Réinitialiser le mot de passe et envoyer un courriel à l\'utilisateur.';

$Definition['Save'] = 'Enregistrer';
$Definition['Search'] = 'Rechercher';
$Definition['Search by user or role.'] = 'Recherchez des utilisateurs en entrant leur nom ou le libellé d\'un statut pour voir tous les utilisateurs associés à ce statut.';
$Definition['seconds'] = 'secondes';
$Definition['Select the file to import'] = 'Choisissez le fichier à importer';
$Definition['Select the import source'] = 'Choisissez le fichier à importer';
$Definition['Settings'] = 'Paramètres';
$Definition['Show unfollowed categories'] = 'Voir les catégories non suivies';
$Definition['Sign Out'] = 'Se déconnecter';
$Definition['SignIn'] = 'Connexion';
$Definition['Sink'] = 'Déclasser';
$Definition['SMTP Host'] = 'Hôte SMTP';
$Definition['SMTP Password'] = 'Mot de passe SMTP';
$Definition['SMTP Port'] = 'Port SMTP';
$Definition['SMTP Security'] = 'Sécurité SMTP';
$Definition['SMTP User'] = 'Utilisateur SMTP';
$Definition['Spam'] = 'Spam';
$Definition['SSL'] = 'SSL';

$Definition['Target'] = 'Cible';
$Definition['Temporary (302)'] = 'Temporaire (302)';
$Definition['TermsOfService'] = 'Conditions d\'Utilisation';
$Definition['TermsOfServiceText'] = "
   <p>En utilisant ce service, vous acceptez de ne pas publier de message qui soit délibérément faux et/ou diffamatoire, inapproprié, abusif, vulgaire, incitant à la haine, insultant, obscène, profane, orienté sexuellement, menaçant, portant atteinte à la liberté d'autrui, ou contraire à la loi. Vous acceptez également de ne pas publier de contenu soumis au droit d'auteur, à moins que celui soit détenu par vous.</p>
   
   <p>Nous nous réservons le droit de révéler votre identité (ou les informations permettant de vous identifier) en cas de plainte ou d'action en justice résultant d'un message que vous avez publié. Nous conservons toutes les adresses IP permettant d'accéder à ce forum.</p>
   
   <p>Les publicités, les chaînes et les sollicitations commerciales sont interdites.</p>
   
   <p>Nous nous réservons le droit de modifier, déplacer ou supprimer tout contenu pour quelque raison que ce soit. Nous nous réservons également le droit de bannir un utilisateur ou de clôturer le compte de n'importe quel utilisateur qui ne respecterait pas les présentes conditions.</p>
   
   <p>Pour participer à la communauté, vous devez avoir 13 ans au minimum.</p>
";
$Definition['The %s Authenticator does not have any custom configuration options.'] = 'La méthode d\'authentification %s ne dispose pas d\'options de configuration.';
$Definition['The addon could not be enabled because it generated a fatal error: <pre>%s</pre>'] = 'L\'extension n\'a pu être activée, car elle a générée une erreur fatale : <pre>%s</pre>';
$Definition['The banner logo appears at the top of your forum.'] = 'Le logo du bandeau apparaît en haut de votre forum.';
$Definition['The banner title appears on the top-left of every page. If a banner logo is uploaded, it will replace the banner title on user-facing forum pages.'] = 'Le titre du bandeau apparaît en haut à gauche de chaque page. Si un logo de bandeau a été téléchargé, il remplacera le titre du bandeau dans l\'interface utilisateur des pages du forum.';
$Definition['The file failed to upload.'] = 'Le fichier n\'a pu être téléchargé.';

$Definition['The homepage was saved successfully.'] = 'La page d\'accueil a été enregistrée correctement.';
$Definition['The page you were looking for could not be found.'] = 'La page que vous recherchez n\'a pu être trouvée.';
$Definition['The Vanilla 2 Exporter'] = 'L\'exporteur Vanilla 2';
$Definition['ThemeHelp'] = 'Les thèmes vous permettent de modifier l\'apparence de votre forum.<br />Une fois qu\'un thème a été ajouté à votre dossier %s, vous pouvez l\'activer ici.';
$Definition['Themes'] = 'Thèmes';
$Definition['Theming Overview'] = 'Aperçu des Thèmes';
$Definition['There are no items awaiting moderation at this time.'] = 'Aucun contenu n\'est en attente de modération pour le moment.';
$Definition['This category has custom permissions.'] = 'Cette catégorie a des autorisations personnalisées.';
$Definition['This category is archived.'] = 'Cette catégorie est archivée.';
$Definition['This Database'] = 'Cette Base de Données';
$Definition['This plugin helps locale package development.'] = 'Cette extension vous aide à développer des Packs de Langues. Cette extension conserve un Pack de Langue fonctionnel à l\'emplacement suivant : <code>%s</code>.';
$Definition['TLS'] = 'TLS';
$Definition['Tools'] = 'Outils';
$Definition['Transport error: %s'] = 'Une erreur fatale est survenue pendant l\'exécution de la requête.<br />Le serveur a renvoyé l\'erreur suivante : %s';
$Definition['Type'] = 'Type';

$Definition['Unlimited'] = 'Illimitées';
$Definition['Unannounce'] = 'Enlever l\'annonce';
$Definition['Unsink'] = 'Remonter';
$Definition['Upload'] = 'Transférer';
$Definition['Use an SMTP server to send email'] = 'Utiliser un serveur SMTP pour envoyer des courriels';
$Definition['Use Categories'] = 'Utiliser les Catégories';
$Definition['Use categories to organize discussions'] = 'Utiliser les catégories pour organiser les discussions';
$Definition['Use My Current Password'] = 'Utiliser mon Mot de passe actuel';
$Definition['Use the content at this url as your homepage.'] = 'Votre "page d\'accueil" est ce que les gens voient quand ils visitent <strong>%s</strong>. Nous utilisons "Toutes les discussions" comme page d\'accueil par défaut, mais vous pouvez la changer comme bon vous semble. Voici quelques options souvent usitées:';
$Definition['User'] = 'Utilisateur';
$Definition['User Registration Settings'] = 'Paramètres d\'enregistrement des Utilisateurs';
$Definition['Username'] = 'Pseudo';
$Definition['Users'] = 'Utilisateurs';
$Definition['User Count'] = 'Utilisateurs';
$Definition['Users will be assigned to this role until they\'ve confirmed their email addresses.'] = 'Les utilisateurs seront affectés à ce statut jusqu\'à ce qu\'ils aient confirmé leur adresse email.';

$Definition['ValidateRequired'] = 'Champs obligatoire requis.';
$Definition['ValidateOneOrMoreArrayItemRequired'] = 'Cochez au moins une des cases requises.';
$Definition['Vanilla'] = 'Vanilla';
$Definition['Vanilla.Archive.Description'] = 'Vous pouvez choisir d\'archiver les discussions du forum antérieures à une certaine date. Les discussions archivées sont clôturées de manière effective et n\'acceptent pas de nouvelles publications.';
$Definition['Vanilla.Categories.MaxDisplayDepth'] = 'Placez les catégories imbriquées dans une liste délimitée par des virgules quand elles ont %1$s';
$Definition['Version'] = 'Version';
$Definition['Version %s'] = 'Version %s';
$Definition['version %s'] = 'version %s';
$Definition['View'] = 'Visualiser';
$Definition['Views'] = 'Vues';
$Definition['View Page'] = 'Voir la Page';
$Definition['Visit Site'] = 'Visiter le Site';

$Definition['Warning'] = 'Avertissement';
$Definition['We will attempt to use the local mail server to send email by default. If you want to use a separate SMTP mail server, you can configure it below.'] = 'Nous allons tenter d\'utiliser le serveur de courrier local pour envoyer des courriels par défaut. Si vous souhaitez utiliser un serveur de messagerie SMTP distinct, vous pouvez le configurer ci-dessous.';
$Definition['What\'s the Buzz?'] = 'Quoi de neuf ?';
$Definition['Within'] = 'Dans l\'intervalle de';

$Definition['You are currently only viewing categories that you follow.'] = 'Vous voyez actuellement uniquement les catégories que vous suivez.';
$Definition['You can always use your password at<a href="%1$s">%1$s</a>.'] = 'Si jamais vous êtes bloqué hors du forum, vous pouvez toujours vous connecter à <a href="%1$s">%1$s</a> en utilisant votre email et mot de passe d\'origine de Vanilla';
$Definition['You can make the categories page your homepage.'] = 'Vous pouvez définir la page des catégories comme votre page d\'accueil principale <a href="%s">ici</a>.';
$Definition['You can place files in your /uploads folder.'] = 'Si votre fichier est trop volumineux à télécharger directement sur cette page, vous pouvez le placer dans votre répertoire /uploads.<br />Assurez-vous que le nom du fichier commence par le terme <b>«export»</b> et se termine par l\'extension <b>.txt</b> ou <b>.gz</b>.';
$Definition['You cannot remove the only remaining category that allows discussions'] = 'Vous ne pouvez pas supprimer la seule catégorie restante qui permet de créer des discussions.';
$Definition['Your changes have been saved successfully.'] = 'Vos modifications ont bien été prises en compte.';
$Definition['Your changes have been saved.'] = 'Vos modifications ont été enregistrées.';
$Definition['Your default locale won\'t display properly'] = 'Votre pack de langue par défaut ne s\'affiche pas correctement car il n\'a pas été activé préalablement. Veuillez activer : %s.';
$Definition['Your settings have been saved.'] = 'Vos paramètres ont été enregistrés.';

/**
* Bienvenue (Getting Started)
**/
$Definition['Here\'s how to get started:'] = 'Voici comment commencer :';

$Definition['Welcome to your Dashboard'] = 'Bienvenue dans votre Tableau de bord';
$Definition['This is the administrative dashboard for your new community. Check out the configuration options to the left: from here you can configure how your community works. <b>Only users in the "Administrator" role can see this part of your community.</b>'] = 'Ceci est le tableau de bord de gestion de votre communauté en ligne.<br />Jetez un coup d\'oeil sur les options de configuration dans la barre latérale à gauche :<br />à partir de là, vous pouvez configurer la façon dont votre communauté fonctionne.<br /><b>Seuls les utilisateurs avec un statut d\'Administrateur<br />peuvent voir l\'espace de gestion de votre communauté.</b>';

$Definition['Where is your Community Forum?'] = 'Où se situe le forum de votre communauté ?';
$Definition['Access your community forum by clicking the "Visit Site" link on the top-left of this page, or by '] = 'Accédez à l\'espace de discussion de votre communauté en cliquant sur le lien "Visitez le Site" en haut à gauche de cette page, ou en ';
$Definition['clicking here'] = 'cliquant ici';
$Definition['. The community forum is what all of your users &amp; customers will see when they visit '] = '.<br />L\'espace de discussion de votre communauté est tout ce que vos utilisateurs & clients verront quand ils visiteront l\'adresse ';

$Definition['Organize your Categories'] = 'Organisez vos Catégories';
$Definition['Discussion categories are used to help your users organize their discussions in a way that is meaningful for your community.'] = 'Les Catégories de discussion sont utilisées pour aider vos utilisateurs à organiser leurs discussions d\'une façon qui est significative pour votre communauté.';

$Definition['Customize your Public Profile'] = 'Personnalisez votre Profil Public';
$Definition['Everyone who signs up for your community gets a public profile page where they can upload a picture of themselves, manage their profile settings, and track cool things going on in the community.'] = 'Chaque personne qui s\'inscrit dans votre communauté aura une page de profil publique, qui lui permettra de télécharger une photo de profil, de gérer ses paramètres de profil, et de suivre les choses intéressantes qui se passent dans la communauté.';
$Definition[' You should '] = '<br />Vous devriez ';
$Definition['customize your profile now'] = 'personnaliser votre profil dès maintenant';

$Definition['Start your First Discussion'] = 'Démarrez votre première discussion';
$Definition['Get the ball rolling in your community by '] = 'Ouvrez la voie à votre communauté en ';
$Definition['starting your first discussion'] = 'démarrant votre première discussion';
$Definition[' now.'] = ' dès maintenant.';

$Definition['Manage your Plugins'] = 'Gérez vos Extensions';
$Definition['Change the way your community works with plugins. We\'ve bundled popular plugins with the software, and there are more available online.'] = 'Modifier la façon dont votre communauté fonctionne avec des extensions.<br />Nous avons regroupé des modules d\'extension populaires avec cette application,<br />et il y en a bien d\'autres accessibles en ligne.';

/**
* Plugins par Défaut
**/
// <Embed> Vanilla
$Definition['&lt;Embed&gt; Vanilla'] = '&lt;Embed&gt; Vanilla';
$Definition['To embed your Vanilla community forum into a remote web application, use the forum embed code or one of the forum embed plugins below.'] = 'Pour intégrer le forum Vanilla de votre communauté dans une application Web distante, utilisez le code d\'intégration du forum ou l\'un des plugins d\'intégration ci-dessous.';
$Definition['Make sure to use a forum theme that meshes well with the look and feel of the remote site.'] = 'Assurez-vous d\'utiliser un thème de forum qui s\'accorde bien avec l\'apparence et l\'organisation du site distant.';

// Debugger (Console d'erreurs)
$Definition['Debugger'] = 'Console d\'erreurs';
$Definition['Debug Information'] = 'Informations de Débogage';
$Definition['Canonical Url'] = 'URL canonique (normalisée)';

// Flagging (Signalement de Contenu)
$Definition['Content Flagging'] = 'Signalement de Contenu';
$Definition['Disable Content Flagging'] = 'Désactiver le Signalement de Contenu';
$Definition['Enable Content Flagging'] = 'Activer le Signalement de Contenu';
$Definition['Flagged Content'] = 'Contenu Signalé';
$Definition['Flagged Items'] = 'Éléments signalés';
$Definition['FlaggedContent'] = 'Le contenu suivant a été signalé par les utilisateurs afin d\'être examiné par les modérateurs.';
$Definition['Flagging'] = 'Signalement de Contenu';
$Definition['Flagging Settings'] = 'Paramètres du Signalement de Contenu';
$Definition['FlagQueueEmpty'] = 'Il n\'y a aucun élément en attente de modération en ce moment.';
$Definition['The following content has been flagged by users for moderator review.'] = 'Le contenu suivant a été signalé par des utilisateurs afin d\'être examiné par un modérateur.';

// Tagging
$Definition['Tagging'] = 'Marquage de Contenu';
$Definition['Enable Tagging'] = 'Activer le Marquage de Contenu';
$Definition['Disable Tagging'] = 'Désactiver le Marquage de Contenu';
$Definition['Tags are keywords that users can assign to discussions to help categorize their question with similar questions.'] = 'Les étiquettes <i>("tags")</i> sont des mots-clés que les utilisateurs peuvent affecter à des discussions pour aider à classer leurs questions avec des questions similaires.';
$Definition['Search for a tag.'] = 'Rechercher sur tout ou partie d\'une étiquette <i>("tag")</i>.';
$Definition['Click a tag name to edit. Click x to remove.'] = 'Cliquez sur le nom de l\'étiquette <i>("tag")</i> à modifier. Cliquez sur X pour supprimer.';
$Definition['%s tag(s) found.'] = '%s étiquette(s) trouvée(s).';
$Definition['There are no tags in the system yet.'] = 'Aucune étiquette n\'est actuellement répertoriée dans le système.';

// Vanilla Statistics
$Definition['Vanilla Statistics'] = 'Statistiques Vanilla';
$Definition['Vanilla Statistics Plugin'] = 'Module de Statistiques de Vanilla';
$Definition['Verified!'] = 'Vérifié !';
$Definition['About Vanilla Statistics'] = 'À propos de Vanilla Statistiques';
$Definition['About.DisableStatistics'] = 'Si vous devez désactiver cette collecte de données pour quelque raison commerciale que ce soit, vous pouvez désactiver ce module en ajoutant la ligne suivante à votre fichier de configuration : <code>$Configuration[\'Garden\'][\'Analytics\'][\'Enabled\'] = FALSE;</code>';
$Definition['About.VanillaStatistics'] = 'Il est important, pour que ce logiciel gratuit et open-source continue à évoluer, que nous puissions mesurer avec précision la portée et l\'efficacité de Vanilla. Nous vous demandons, s\'il vous plaît, ne pas désactiver la collecte de ces données.';
$Definition['PageViews'] = 'Pages Vues';
$Definition['Start'] = 'Début';
$Definition['Statistics'] = 'Statistiques';
$Definition['Statistics Documentation'] = 'Documentation du module Statistiques';
$Definition['The Vanilla Statistics plugin turns your forum\'s dashboard into an analytics reporting tool'] = 'Le module Statistiques de Vanilla transforme le tableau de bord de votre forum dans un outils d\'analyse et de rapport statistiques, vous permettant de visualiser l\'activité de votre forum sur des périodes données. Vous pouvez <a href="http://vanillaforums.org/docs/vanillastatistics">en savoir plus sur Vanilla Statistics</a> dans notre documentation.';

$Definition['Vanilla Statistics are currently disabled'] = 'Le module Vanilla Statistics est actuellement désactivé';
$Definition['Garden.StatisticsDisabled'] = 'Vous avez désactivé spécifiquement le module Vanilla Statistics dans votre fichier de configuration.';

/**
* Plugins de connexion
**/
// Open ID (à activer pour utiliser
$Definition['Enable OpenID'] = 'Activer OpenID';
$Definition['Disable OpenID'] = 'Désactiver OpenID';
$Definition['OpenID Settings'] = 'Paramètres OpenID';
$Definition['This plugin allows users to sign in with OpenID. <b>Make sure you click Settings after enabling this plugin to enable OpenID signin</b>.'] = 'Cette extension vous permet de vous connecter à l\'aide d\'OpenID. <b>Assurez-vous de cliquer sur Paramètres après avoir activé cette extension pour pouvoir autoriser la connexion via OpenID.</b>';

// Facebook Connect
$Definition['Facebook Settings'] = 'Paramètres Facebook';
$Definition['Facebook Connect allows users to sign in using their Facebook account.'] = '<b>Facebook Connect</b> permet aux utilisateurs de se connecter en utilisant leur compte Facebook.<br /><b>Vous devez enregistrer votre application avec Facebook pour que cette extension fonctionne.</b>';
$Definition['Application ID'] = 'ID de l\'application / Clé de l\'API';
$Definition['Application Secret'] = 'Clé secrète';

// Google Sign In
$Definition['Enable Google Sign In'] = 'Activer Google Sign In';
$Definition['Disable Google Sign In'] = 'Activer Google Sign In';
$Definition['Google Sign In Settings'] = 'Paramètres de connexion avec Google';
$Definition['This plugin allows users to sign in with their Google accounts. <b>Make sure you click Settings after enabling this plugin to enable Google signin</b>.'] = 'Cette extension permet aux utilisateurs de se connecter avec leur compte Google. <b>Assurez-vous de cliquer sur Paramètres après avoir activé cette extension pour pouvoir autoriser la connexion via Google accounts.</b>';

// Twitter Connect
$Definition['Twitter Settings'] = 'Paramètres Twitter';
$Definition['Twitter Connect allows users to sign in using their Twitter account.'] = '<b>Twitter Connect</b> permet aux utilisateurs de se connecter en utilisant leur compte Twitter.<br /><b>Vous devez enregistrer votre application avec Twitter pour que cette extension fonctionne.</b>';
$Definition['Consumer Key'] = 'Clé de l\'Utilisateur <small>(Consumer Key)</small>';
$Definition['Consumer Secret'] = 'Clé secrète <small>(Consumer secret)</small>';

/**
* Plugins additionnels
**/
// Locale Developer
$Definition['Locale Developer'] = 'Locale Developer';
$Definition['Locale Developer Settings %s.'] = 'Locale Developer - Paramètres %s.';

$Definition['For more help on localization check out the page <a href="%s">here</a>.'] = 'Pour plus d\'aide sur la traduction, <a href="%s">consultez cette page</a>.';
$Definition['Locale info file settings.'] = '<p>Lorsque vous générez le fichier zip, vous pouvez définir les informations ci-dessous pour les paramètres régionaux.</p> <p>Vous pouvez télécharger une archive zip du pack de langue en cliquant <a href="%s">ici</a>.</p>';

$Definition['Locale Key (Folder)'] = 'Emplacement du Pack de Langue (dossier)';
$Definition['Locale Name'] = 'Nom du Pack de Langue';
$Definition['Capture definitions throughout the site. You must visit the pages in the site in order for the definitions to be captured. The captured definitions will be put in the <code>captured.php</code> and <code>captured_admin.php</code>.'] = 'Capturer les définitions du site. Vous devez parcourir les pages du site afin que les définitions puissent être capturées. Les définitions capturées seront listées dans les fichiers <code>captured.php</code> et <code>captured_admin.php</code>.';

$Definition['Choose a locale pack'] = 'Choisissez un Pack de Langue';
$Definition['Capture locale pack changes.'] = 'Capture les changement entre un de vos Packs de Langue et Locale Developer. Les modifications seront listées dans le fichier <code>changes.php</code>.';
$Definition['Copy locale pack.'] = 'Copier les définitions d\'un Pack de Langue vers Locale Developer. Les définitions seront listées dans le fichier <code>copied.php</code>.';
$Definition['Remove locale developer files.'] = 'Supprimer les fichiers Locale Developer et réinitialiser vos modifications.';