<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2011-11-30 04:27:02 **/

$LocaleInfo['French'] = array (
  'Locale' => 'fr-FR',
  'Name' => 'French',
  'Description' => 'française',
  'Version' => '2.0.18.1',
  'Author' => 'Arachnos',
  'AuthorEmail' => 'arachnos@creative-tarentula.net',
  'AuthorUrl' => 'http://www.creative-tarentula.net',
  'License' => 'Creative Commons - CC BY-SA 2.0'
);

