<?php if (!defined('APPLICATION')) exit();
/** This file was generated by the Locale Developer plugin on 2011-02-08 04:12:08 **/

$Definition['&larr; All Discussions'] = '&larr; Toutes les Discussions';

$Definition['%s and you'] = 'Entre %s et vous';
$Definition['%s comment'] = '%s commentaire';
$Definition['%s comments'] = '%s commentaires';
$Definition['%s discussions'] = '%s discussions';
$Definition['%s message'] = '%s message';
$Definition['%s new'] = '%s nouveau';
$Definition['%s New'] = '%s Nouveau';

$Definition['(less)'] = '(moins)';
$Definition['(more)'] = '(plus)';

$Definition['<General Error>'] = '<Erreur Générale>';

$Definition['About'] = 'À propos…';
$Definition['Activity'] = 'Activité';
$Definition['Activity.Comment'] = 'Commenter';
$Definition['Activity.ConversationMessage.FullHeadline'] = '%1$s avez envoyé un %8$s à %3$s.';
$Definition['Activity.ConversationMessage.ProfileHeadline'] = '%1$s vous a envoyé un %8$s à %3$s.';
$Definition['Activity.Delete'] = 'Supprimer';
$Definition['Activity.Import.FullHeadline'] = '%1$s avez importé des données.';
$Definition['Activity.Import.ProfileHeadline'] = '%1$s a importé des données.';
$Definition['Activity.Join.FullHeadline'] = '%1$s avez rejoint la communauté.';
$Definition['Activity.Join.ProfileHeadline'] = '%1$s s\'est connecté.';
$Definition['Activity.NewDiscussion.FullHeadline'] = '%1$s avez commencé une %8$s.';
$Definition['Activity.NewDiscussion.ProfileHeadline'] = '%1$s a commencé une %8$s.';
$Definition['Activity.PictureChange.FullHeadline'] = '%1$s avez changé %6$s photo de profil.';
$Definition['Activity.PictureChange.ProfileHeadline'] = '%1$s a changé %6$s Photo de profil.';
$Definition['Activity.RoleChange.FullHeadline'] = '%1$s avez changé les autorisations de %3$s.';
$Definition['Activity.RoleChange.ProfileHeadline'] = '%$s a changé les autorisations de %3$s.';
$Definition['Activity.NewRoles'] = '%1$s a ajouté le %2$s de %3$s  .';
$Definition['Add Comment'] = 'Rédiger un commentaire';
$Definition['Add a Comment'] = 'Rédiger un commentaire';
$Definition['Add Info &amp; Create Account'] = 'Créez votre Compte';
$Definition['Add People to this Conversation'] = 'Ajouter des Personnes';
$Definition['All Categories'] = 'Toutes les Catégories';
$Definition['All Conversations'] = 'Tous les Messages';
$Definition['All Discussions'] = 'Toutes les Discussions';
$Definition['Allow other members to see your email?'] = 'Autoriser les autres membres à voir votre adresse email ?';
$Definition['Announce'] = 'Annoncer';
$Definition['Announcement'] = 'Message d\'information';
$Definition['Apply for Membership'] = 'S\'inscrire';
$Definition['Are you sure you want to do that?'] = 'Êtes-vous sûr de vouloir faire cela ?';
$Definition['at'] = 'at';
$Definition['Autoriser les autres membres à voir votre adresse email ?'] = 'Autoriser les autres membres à voir votre adresse email ?';

$Definition['Back to Discussions'] = 'Retour aux Discussions';
$Definition['Bookmark'] = 'Favori';
$Definition['By uploading a file you certify that you have the right to distribute this picture and that it does not violate the Terms of Service.'] = 'En téléchargeant un fichier, vous certifiez que vous avez le droit de distribuer cette image et qu\'elle ne viole pas les Conditions d\'utilisation.';

$Definition['Cancel'] = 'Annuler';
$Definition['Categories'] = 'Catégories';
$Definition['Category'] = 'Category';
$Definition['Change My Password'] = 'Modifier mon Mot de passe';
$Definition['Change My Picture'] = 'Modifier ma Photo de profil';
$Definition['Change Password'] = 'Modifier le Mot de passe';
$Definition['Change Picture'] = 'Modifier la Photo de profil';
$Definition['Choose a name to identify yourself on the site.'] = 'Choisissez un nom pour vous identifier sur le forum.';
$Definition['Close'] = 'Fermer';
$Definition['Closed'] = 'Fermé';
$Definition['Comment'] = 'Commenter';
$Definition['Comment by %s'] = 'Commentaire de %s';
$Definition['Confirm'] = 'Confirmer';
$Definition['Confirm Password'] = 'Confirmer le Mot de passe';
$Definition['Connect'] = 'Connectez-vous';
$Definition['Conversations'] = 'Conversations';
$Definition['Create One.'] = 'S\'inscrire';

$Definition['Dashboard'] = 'Tableau de bord';
$Definition['Date.DefaultDayFormat'] = '%e %B';
$Definition['Date.DefaultFormat'] = '%e %B %Y';
$Definition['Date.DefaultTimeFormat'] = '%k:%M';
$Definition['Date.DefaultYearFormat'] = '%B %Y';
$Definition['Delete'] = 'Supprimer';
$Definition['Delete Account'] = 'Supprimer le Compte';
$Definition['Delete Conversation'] = 'Supprimer la Conversation';
$Definition['Delete Discussion'] = 'Supprimer la Discussion';
$Definition['Discussion Title'] = 'Titre';
$Definition['Discussions'] = 'Discussions';
$Definition['Don\'t have an account? %s'] = 'Pas encore inscrit ? %s';
$Definition['dot'] = 'dot';
$Definition['Drag around and resize the square below to define your thumbnail icon.'] = 'Drag around and resize the square below to define your thumbnail icon.';

$Definition['Edit Account'] = 'Modifier le Compte';
$Definition['Edit My Account'] = 'Paramètres du Compte';
$Definition['Edit My Thumbnail'] = 'Modifier ma Miniature';
$Definition['Edit Thumbnail'] = 'Modifier la Miniature';
$Definition['Email'] = 'Email';
$Definition['Email/Username'] = 'Adresse Email / Nom d\'Utilisateur';
$Definition['Email Notifications'] = 'Notifications Email';
$Definition['Edit Preferences'] = 'Modifier les Préférences de Notification';
$Definition['Not much happening here, yet.'] = 'Il ne se passe pas grand chose par ici, pour l\'instant.';
$Definition['Email Unavailable'] = 'Email indisponible';
$Definition['Enregistrer'] = 'Enregistrer';
$Definition['Enter your Email address'] = 'Entrez votre adresse Email';
$Definition['Enter your email address'] = 'Entrez votre adresse Email';
$Definition['Enter your Email address or username'] = 'Entrez votre adresse Email<br />ou votre Nom d\'Utilisateur';
$Definition['Enter Your OpenID Url'] = 'Entrez votre adresse OpenID';
$Definition['ErrorCredentials'] = 'Désolé, aucun compte n\'est associé à l\'adresse email et au mot de passe que vous avez entrés.';

$Definition['Female'] = 'Femme';
$Definition['Femme'] = 'Femme';
$Definition['Flag'] = 'Signaler un abus';
$Definition['Flag this Discussion'] = 'Signaler cette Discussion';
$Definition['Flag this!'] = 'Signaler ce contenu !';
$Definition['Forgot?'] = '<br /><div style="padding: 6px; margin-bottom: 10px;">Mot de passe oublié ?</div>';

$Definition['Gender'] = 'Sexe';
$Definition['GenderSuffix.First.m'] = '';
$Definition['GenderSuffix.Third.m'] = '';
$Definition['Go'] = 'Ok';
$Definition['GuestModule.Message'] = 'Si vous souhaitez rejoindre la communauté, cliquez sur un des boutons ci-dessous.';

$Definition['he'] = 'il';
$Definition['his'] = 'son';
$Definition['Homme'] = 'Homme';
$Definition['Howdy, Stranger!'] = 'Bienvenue dans la Communauté !';

$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="%s">terms of service</a>'] = 'J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="%s">Conditions d\'Utilisation du Forum</a>';
$Definition['I agree to the <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">terms of service</a>'] = 'I agree to the <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">terms of service</a>';
$Definition['I remember now!'] = 'Je m\'en souviens maintenant !';
$Definition['In this Conversation'] = 'Dans cette Conversation privée';
$Definition['In this Discussion'] = 'Dans cette Discussion';
$Definition['Inbox'] = 'Boîte de Réception';
$Definition['Internal'] = 'Interne';

$Definition['J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">Conditions d\'Utilisation du Forum</a>'] = 'J\'accepte les <a id="TermsOfService" class="Popup" target="terms" href="/forum/dashboard/home/termsofservice">Conditions d\'Utilisation du Forum</a>';
$Definition['Joined'] = 'Inscription';
$Definition['Just you!'] = 'Seulement vous !';

$Definition['Keep me signed in'] = 'Se souvenir de moi';

$Definition['Last Active'] = 'Activité';

$Definition['M\'avertir quand je reçois un message privé.'] = 'M\'avertir quand je reçois un message privé.';
$Definition['M\'avertir quand je suis ajouté à des conversations privées.'] = 'M\'avertir quand je suis ajouté à des conversations privées.';
$Definition['M\'avertir quand quelqu\'un commente mes discussions favorites.'] = 'M\'avertir quand quelqu\'un commente mes discussions favorites.';
$Definition['M\'avertir quand quelqu\'un commente mes discussions.'] = 'M\'avertir quand quelqu\'un commente mes discussions.';
$Definition['M\'avertir quand quelqu\'un me mentionne dans des commentaires.'] = 'M\'avertir quand quelqu\'un me mentionne dans des commentaires.';
$Definition['M\'avertir quand quelqu\'un me mentionne dans le titre d\'une discussion.'] = 'M\'avertir quand quelqu\'un me mentionne dans le titre d\'une discussion.';
$Definition['M\'avertir quand quelqu\'un répond aux commentaires sur mon mur.'] = 'M\'avertir quand quelqu\'un répond aux commentaires sur mon mur.';
$Definition['M\'avertir quand quelqu\'un écrit sur mon mur.'] = 'M\'avertir quand quelqu\'un écrit sur mon mur.';
$Definition['Male'] = 'Homme';
$Definition['Most recent by %1$s'] = 'Dernier message par %1$s';
$Definition['My Bookmarks'] = 'Mes favoris';
$Definition['My Discussions'] = 'Mes discussions';
$Definition['My Drafts'] = 'Mes brouillons';
$Definition['My Preferences'] = 'Préférences de notifications';

$Definition['Name Unavailable'] = 'Name Unavailable';
$Definition['New Password'] = 'Nouveau Mot de passe';
$Definition['No discussions were found.'] = 'Aucune discussion n\'a été trouvée.';
$Definition['Notifications'] = 'Notifications';
$Definition['Notify me of private messages.'] = 'M\'avertir quand je reçois un message privé.';
$Definition['Notify me when I am added to private conversations.'] = 'M\'avertir quand je suis ajouté à des conversations privées.';
$Definition['Notify me when people comment on my bookmarked discussions.'] = 'M\'avertir quand quelqu\'un commente mes discussions favorites.';
$Definition['Notify me when people comment on my discussions.'] = 'M\'avertir quand quelqu\'un commente mes discussions.';
$Definition['Notify me when people mention me in comments.'] = 'M\'avertir quand quelqu\'un me mentionne dans des commentaires.';
$Definition['Notify me when people mention me in discussion titles.'] = 'M\'avertir quand quelqu\'un me mentionne dans le titre d\'une discussion.';
$Definition['Notify me when people reply to my wall comments.'] = 'M\'avertir quand quelqu\'un répond aux commentaires sur mon mur.';
$Definition['Notify me when people write on my wall.'] = 'M\'avertir quand quelqu\'un écrit sur mon mur.';

$Definition['Old Password'] = 'Ancien mot de passe';
$Definition['Original'] = 'Original';
$Definition['Or you can...'] = 'Ou vous pouvez...';

$Definition['Partager'] = 'Partager';
$Definition['Password'] = 'Mot de Passe';
$Definition['Passwords don\'t match'] = 'Les mots de passe ne correspondent pas';
$Definition['Permalink'] = 'Lien permanent';
$Definition['permalink'] = 'lien permanent';
$Definition['Post Comment'] = 'Publier le Commentaire';
$Definition['Post Discussion'] = 'Publier la Discussion';
$Definition['Powered by Vanilla'] = 'Propulsé par Vanilla';
$Definition['Preview'] = 'Aperçu';

$Definition['Reason'] = 'Raison';
$Definition['Recent Activity'] = 'Activité Récente';
$Definition['Recipients'] = 'Destinataires';
$Definition['Remember me on this computer'] = 'Se souvenir de moi sur cet ordinateur';
$Definition['Remove My Picture'] = 'Supprimer ma Photo de profil';
$Definition['Remove Picture'] = 'Supprimer la Photo de profil';
$Definition['Reopen'] = 'Réouvrir';
$Definition['Request a new password'] = 'Demander un nouveau mot de passe';
$Definition['Reset my password'] = 'Réinitialiser mon Mot de passe';
$Definition['Rester connecté'] = 'Rester connecté';
$Definition['Roles'] = 'Statuts';

$Definition['Save'] = 'Save';
$Definition['Save Draft'] = 'Enregistrer comme brouillon';
$Definition['Save Preferences'] = 'Enregistrer';
$Definition['Search'] = 'Recherche';
$Definition['Security Check'] = 'Contrôle de Sécurité';
$Definition['Select an image on your computer (2mb max)'] = 'Choisissez une image sur votre ordinateur (2 Mo max.)';
$Definition['Send %s a Message'] = 'Envoyer un message à %s';
$Definition['Send Message'] = 'Envoyer le Message';
$Definition['Share'] = 'Partager';
$Definition['Sign In'] = 'Connexion';
$Definition['Sign In with Google'] = 'Connectez-vous avec Google';
$Definition['Sign In with OpenID'] = 'Connectez-vous avec OpenID';
$Definition['Sign Out'] = 'Se déconnecter';
$Definition['Sign Up'] = 'Je m\'inscris';
$Definition['somebody'] = 'quelqu\'un';
$Definition['Start a New Conversation'] = 'Nouveau Message';
$Definition['Start a New Discussion'] = 'Nouvelle Discussion';
$Definition['Start Conversation'] = 'Envoyer le message';
$Definition['Started by %1$s'] = 'Commencée par %1$s';

$Definition['Thumbnail'] = 'Thumbnail';
$Definition['This discussion has been closed.'] = 'Cette discussion a été fermée.';
$Definition['This image has been resized to fit in the page. Click to enlarge.'] = 'Cette image a été redimensionnée pour tenir dans la page. Cliquez pour agrandir.';
$Definition['This page requires Javascript.'] = 'Cette page nécessite que le Javascript soit activé pour pouvoir fonctionner correctement.';
$Definition['Transport error: %s'] = 'Une erreur fatale est survenue lors de l\'exécution de la requête.<br />Le serveur a renvoyé la réponse suivante: %s';
$Definition["To use reCAPTCHA you must get an API key from <a href='http://recaptcha.net/api/getkey'>http://recaptcha.net/api/getkey</a>"] = 'Pour utiliser reCAPTCHA vous devez obtenir une clé API sur <a href="http://recaptcha.net/api/getkey">http://recaptcha.net/api/getkey</a>';

$Definition['Upload'] = 'Télécharger';
$Definition['Users Count'] = 'Utilisateurs';
$Definition['Username'] = 'Nom d\'Utlisateur';
$Definition['UsernameError'] = 'Le Nom d\'Utilisateur ne peut contenir que des lettres, des chiffres, des tirets bas (_), et doit contenir entre 3 et 20 caractères de long.';

$Definition['Visits'] = 'Visites';

$Definition['wall'] = 'mur';
$Definition['Write a comment'] = 'Commenter';
$Definition['Write Comment'] = 'Rédiger un commentaire';
$Definition['Write something about yourself...'] = 'Écrivez quelque chose à propos de vous...';

$Definition['You'] = 'Vous';
$Definition['You do not have any conversations.'] = 'Vous n\'avez aucune conversation en cours.';
$Definition['You do not have any notifications yet.'] = 'Vous n\'avez aucune notification pour l\'instant.';
$Definition['You must agree to the terms of service.'] = 'Vous devez accepter les Conditions d\'Utilisation du Forum.';
$Definition['your'] = 'votre';

